### PR TITLE
RESTEASY-2463 cleanup old org.codehaus.jackson dependencies

### PR DESCRIPTION
**Pull request by vaibhavpatel**

### CODE REVIEW

**Comment by vaibhavpatel** [comment]
@asoldano Thanks do much for looking at this! addressed your change request

**Comment by vaibhavpatel** [comment]
Yes, i agree

**Comment by vaibhavpatel** [comment]
@asoldano Thanks for looking at this! addressed your change request

**Comment by asoldano** [comment]
merged, thanks!

**Pull request merged**
