### PR TITLE
[RESTEASY-2624] Built in MicroProfile ConfigSource should let user override default ordinal

### PR DESCRIPTION
**Pull request by NicoNes**
Issue: https://issues.redhat.com/browse/RESTEASY-2624

### CODE REVIEW

**Comment by NicoNes** [comment]
Hi Guys,

Is there any good reason to not let `BaseServletConfigSource` implements from `ConfigSource`?

Thanks

**Comment by asoldano** [comment]
@NicoNes thanks for the PR. @ronsigal , @rsearls can you please review?

**Comment by ronsigal** [comment]
Hey @NicoNes,

Nice to see you around RESTEasy. ;-)

It all looks fine to me. I would just say that there should be a note in the User Guide, or no one will know about it.

-Ron

**Comment by NicoNes** [comment]
Hey @ronsigal,

Yes I'm back here !!

We finally started to use the RESTEasy latest version at work so I will try to contribute again when possible.

> I would just say that there should be a note in the User Guide, or no one will know about it.
Yes I will add a note about it.

Do you think we can make `BaseServletConfigSource` implements from `ConfigSource` directly?

**Comment by asoldano** [comment]
@NicoNes @ronsigal @rsearls , we kind of forgot about this; would it be possible to resolve the conflicts and verify this still works. I'd include this in next release which should be fairly soon.

**Comment by NicoNes** [comment]
@asoldano Yes I'll do it :+1:

**Comment by NicoNes** [comment]
@asoldano rebase and conflict resolution are OK but one build is still failling for no clear reason while others are OK. Can you check please.

**Review by ronsigal — APPROVED** [review]

**Comment by ronsigal** [comment]
Thanks, @NicoNes!!

**Pull request merged**
