### PR TITLE
Change http to https in repository references.

### PR DESCRIPTION
**Pull request by ronsigal**

### CODE REVIEW

**Comment by ronsigal** [comment]
Thanks, @asoldano, that's good to know. Unfortunately, I'm getting failures at home, which is why I submitted the PR. And then I downloaded branch 3.6 and also got failures. Weird.

**Comment by ronsigal** [comment]
Well, I'm getting
```
Tests in error: 
  AddSpringResteasyAsResourceRootTest.org.jboss.resteasy.test.spring.deployment.AddSpringResteasyAsResourceRootTest » Deployment
  ContactsDependenciesInDeploymentTest.org.jboss.resteasy.test.spring.deployment.ContactsDependenciesInDeploymentTest » Deployment
  ContextRefreshDependenciesInDeploymentTest.org.jboss.resteasy.test.spring.deployment.ContextRefreshDependenciesInDeploymentTest » Deployment
  JavaConfigDependenciesInDeploymentTest.org.jboss.resteasy.test.spring.deployment.JavaConfigDependenciesInDeploymentTest » Deployment
  JaxrsWithSpringMVCTest.org.jboss.resteasy.test.spring.deployment.JaxrsWithSpringMVCTest » Deployment
  RequestScopedBeanDependenciesInDeploymentTest.org.jboss.resteasy.test.spring.deployment.RequestScopedBeanDependenciesInDeploymentTest » Deployment
  SpringBeanProcessorDependenciesInDeploymentTest.org.jboss.resteasy.test.spring.deployment.SpringBeanProcessorDependenciesInDeploymentTest » Deployment
  SpringLocatingResourceDependenciesInDeploymentTest.org.jboss.resteasy.test.spring.deployment.SpringLocatingResourceDependenciesInDeploymentTest » Deployment
  SpringWebappContextDependenciesInDeploymentTest.org.jboss.resteasy.test.spring.deployment.SpringWebappContextDependenciesInDeploymentTest » Deployment
  TypeMappingDependenciesInDeploymentTest.org.jboss.resteasy.test.spring.deployment.TypeMappingDependenciesInDeploymentTest » Deployment

Tests run: 10, Failures: 0, Errors: 10, Skipped: 0
```
both at home and here. There are also some additional Rx failures here. All of them seem to be related to zip. Weird.

**Comment by ronsigal** [comment]
Also, I got the same results from branch 3.6 at tag 3.6.0.Final. Weird.

**Comment by ronsigal** [comment]
Note. It looks like the failures are correlated with org.jboss.resteasy.utils.TestUtilRxJava and TestUtilSpring. I haven't looked into those classes yet.

**Comment by ronsigal** [comment]
Well, I get
```
[rsigal@localhost 1.3.2]$ jar -tf rxjava-1.3.2.jar
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:126)
	at sun.tools.jar.Main.list(Main.java:1115)
	at sun.tools.jar.Main.run(Main.java:293)
	at sun.tools.jar.Main.main(Main.java:1288)
```
in .m2/repository/io/reactivex/rxjava/1.3.2. When I delete the directory, the same rxjava-1.3.2.jar comes back. Not sure yet where it's coming from, but this is encouraging.

**Comment by ronsigal** [comment]
Ok, I see. TestUtilRxJava is loading three jars:
```
runtimeDependencies.add(mavenUtil.createMavenGavFile("org.jboss.resteasy:resteasy-rxjava:" + System.getProperty("project.version")));
runtimeDependencies.add(mavenUtil.createMavenGavFile("io.reactivex:rxjava:" + getRxJavaVersion()));
runtimeDependencies.add(mavenUtil.createMavenGavFile("io.reactivex:rxjava-reactive-streams:" + getRxJavaReactiveStreamsVersion()));
```
and getRxJavaVersion() returns
```
private static String defaultRxJavaVersion = "1.3.2";
```
But RESTEasy is up to version 1.3.8 by now. rxjava-1.3.2.jar is coming from 
```
https://maven.repository.redhat.com/nexus/content/groups/product-techpreview
```
and it's corrupted somehow. When I update defaultRxJavaVersion to 1.3.8, RxSingleTest passes.

@FroMage, @marekkopecky, did one of you add 
```
TestUtilRxJava.addRxJavaLibraries(war);
```
to RxSingleTest? Why go to all the trouble? Why not just inherit the version from resteasy-dependencies-bom?

**Comment by ronsigal** [comment]
Oh, I see. Those are needed for rxjava 1 and they're not in Wildfly. Hmmm. There's got to be a better way than relying on a system property or a hardcoded default...

**Comment by ronsigal** [comment]
Changing defaultRxJavaVersion to "1.3.8" in TestUtilRxJava and changing defaultSpringVersion to "4.3.22.RELEASE" gives a clean testsuite run.

**Comment by ronsigal** [comment]
Strange. I didn't mean to merge this before letting the test suite run.

**Comment by ronsigal** [comment]
The bad jar is coming from
```
https://maven.repository.redhat.com/nexus/content/groups/product-techpreview
```

**Comment by jbliznak** [comment]
@asoldano @ronsigal  the repository ```https://maven.repository.redhat.com/nexus/content/groups/product-techpreview``` doesn't appear to be available anymore, I would suggest to use ```https://maven.repository.redhat.com/earlyaccess/all/``` instead (on all branches) in https://github.com/resteasy/Resteasy/blob/master/testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/maven/MavenUtil.java#L211-L242 . BTW, there is yet another repository in this file with http instead of https.

> Why not just inherit the version from resteasy-dependencies-bom?

In Maven, you can't inherit properties from imported dependencies BOM, you can inherit properties from (transitive) parent only.

**Pull request closed without merging**
