### PR TITLE
[JBEAP-4899] : RESTEasy should log used Providers and Interceptors in DEBUG level.

### PR DESCRIPTION
**Pull request by panossot**
https://issues.jboss.org/browse/JBEAP-4899

### CODE REVIEW

**Comment by panossot** [comment]
Failure is irrelevant. 

Retest this please.

**Comment by asoldano** [comment]
Hi @panossot , I have two comments here:
1) I tried re-running the testsuite runs, but they failed again, so I suspect there's indeed something in the changes you applied that is causing them
2) the way you implemented the logs is not fine in terms of performances. You should not do something like 

LogMessages.LOGGER.debug(Messages.MESSAGES.interceptorStartMethodCall("org.jboss.resteasy.plugins.providers.jackson","JacksonJsonpInterceptor","aroundWriteTo"));

instead you should be adding @LogMessage annotated methods with proper level and use them directly. The way you did, the i18n messages will always be computed, even if the log configuration is such that they will not eventually be printed.

**Comment by panossot** [comment]
Hello @asoldano. Thank you for your comments. I will do it by adding  @LogMessage annotated methods. It is not ready yet, as some tests are failing..

**Comment by panossot** [comment]
@asoldano : There were some more providers to be annotated. Let's see if it builds.

**Comment by marekkopecky** [comment]
Wouldn't be possible add logging only to one place instead of to all providers? Users could register custom provider to RESTEasy and this custom provider won't be logged.

**Comment by rsvoboda** [comment]
It's too much work and code done in this PR.

I asked Jamez on Hipchat if there is any way how could JBoss logging help - e.g. set  default '@LogMessage(level = Level.DEBUG)' for class / package

I can think of aspects to log method invocation instead of adding @LogMessage and @Message to every method in those classes.

**Comment by marekkopecky** [comment]
AFAIK, MessageBodyReader is selected here:
https://github.com/resteasy/Resteasy/blob/master/resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/AbstractReaderInterceptorContext.java#L52

In my point of view, it would be enough to add proper logging here, example: (this works correctly, I test it with WF):
```
LogMessages.LOGGER.debugUsedMessageBodyReader(reader.getClass().getName().);
```
and to similar places for MessageBodyWriter and Interceptors.

This approach correctly logs also custom providers defined in deployments.

**Comment by panossot** [comment]
According to https://github.com/jboss-logging/jboss-logging/blob/master/src/main/java/org/jboss/logging/LogMessage.java the target is method.

Also, if the proceed method of AbstractReaderInterceptorContext.java is overidden then there will be no logging.

I could limit the Logging Annotations only to the basic methods.

**Comment by panossot** [comment]
On second thoughts maybe marekkopecky's idea would be the best solution. I will implement that one.

**Comment by jamezp** [comment]
These annotations will be ignored unless they are on an interface annotated with `@MessageLogger` or `@MessageBundle`. Adding annotations to random messages won't do anything. The logging tooling generates implementations for logger or bundle interfaces. It's a compile time only tool.

There is also no requirement for debug messages to be internationalized. Therefore all you need to do is log a normal debug message. For example you just need to do something like the following:
```
LogMessages.LOGGER.debugf("Provider: %s", getClass().getName())
```

**Comment by panossot** [comment]
Closing this one. Replaced via https://github.com/resteasy/Resteasy/pull/951.

**Pull request closed without merging**
