### PR TITLE
[RESTEASY-1190] Wrap JSONP response in try-catch block

### PR DESCRIPTION
**Pull request by bedrin**
I suggest wrapping the JSONP callback in a try-catch block.
It will prevent some browsers like MSIE to shown an error window when the specified callback function doesn't exist

### CODE REVIEW

**Comment by ronsigal** [comment]
Hi bedrin,

It looks OK, and the Resteasy testsuite passes.

Could you create a JIRA issue at https://jira.jboss.org/browse/RESTEASY? And correct the one misspelling?

Thanks,
Ron

**Comment by bedrin** [comment]
I have fixed the misprint

**Comment by bedrin** [comment]
Created [RESTEASY-1190](https://issues.jboss.org/browse/RESTEASY-1190)

**Comment by ronsigal** [comment]
Ok, thanks.

**Comment by ronsigal** [comment]
This PR looks good to merge.

**Pull request merged**
