### PR TITLE
Try to get some SSE test results

### PR DESCRIPTION
**Pull request by FroMage**
DO NOT MERGE

Trying to get CI info about failing SSE tests

### CODE REVIEW

**Comment by FroMage** [comment]
I mean, it failed, but in the javadoc stage, due to me forgetting to disable checkstyle due to my added print statements. But the tests did pass.

**Comment by asoldano** [comment]
@FroMage not sure I get your question; feel free to re-run as you wish though

**Comment by FroMage** [comment]
I was wondering if this failed in other branches than master?

**Comment by FroMage** [comment]
No, according to what you pointed me to it was master and 4.5, let's rerun until it fails then…

**Comment by FroMage** [comment]
@asoldano I've restarted it 5 times and not a single failure :(

**Comment by asoldano** [comment]
@FroMage I've restarted it yet another time.. could it be that the additional logs somehow influence this?

**Comment by FroMage** [comment]
I will try removing them, but then the logs are not going to help me much :(

**Comment by FroMage** [comment]
Keeps on passing, even with the logging removed.

**Comment by asoldano** [comment]
This is really strange, I've re-run the jobs for the latest commit on master and it failed: https://travis-ci.org/resteasy/Resteasy/builds/658110452?utm_source=github_status&utm_medium=notification ...

**Comment by ronsigal** [comment]
@FroMage, @asoldano, is the intermittent failure in https://github.com/resteasy/Resteasy/pull/2318 related to whatever instigated this PR?
```
[ERROR] testSSE(org.jboss.resteasy.test.asyncio.SSETest)  Time elapsed: 4.132 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[CHECK]> but was:<[Not closed]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.jboss.resteasy.test.asyncio.SSETest.querySSEAndAssert(SSETest.java:85)
	at org.jboss.resteasy.test.asyncio.SSETest.testSSE(SSETest.java:65)
```

**Comment by asoldano** [comment]
@ronsigal yes... but for some reasons issues are reproduces everywhere except on this PR :-/ I'm closing it now, perhaps we might try with another one, even if I can't explain the reason for this...

**Comment by ronsigal** [comment]
Thanks,@asoldano. The world is going crazy.

**Pull request closed without merging**
