### PR TITLE
[RESTEASY-2884] add doPriv blocks to DefaultConfiguration for Java 2 …

### PR DESCRIPTION
**Pull request by WhiteCat22**
…Security.

I agree to the Apache License 2.0 terms.

### CODE REVIEW

**Comment by WhiteCat22** [comment]
I hope I've done everything correctly, please let me know if I missed anything.

**Comment by jamezp** [comment]
TBH the `ManualClosingApacheHttpClient43Engine` looks wrong anyway :) There is a potential NPE in it.
```java
protected File fileUploadTempFileDir = new File(ConfigurationFactory.getInstance().getConfiguration().getOptionalValue("java.io.tmpdir", String.class).orElse(null));
```

That should really be:
```java
protected File fileUploadTempFileDir = getTempDIr();
....

private static File getTempDir() {
   if (System.getSecurityManager() == null) {
      final Optional<String> value = ConfigurationFactory.getInstance().getConfiguration().getOptionalValue("java.io.tmpdir", String.class);
      return value.map(File::new).orElseGet(() -> new File(System.getProperty("java.io.tmpdir")));
   }
   return AccessController.doPrivileged((PrivilegedAction<File>) () -> {
      final Optional<String> value = ConfigurationFactory.getInstance().getConfiguration().getOptionalValue("java.io.tmpdir", String.class);
      return value.map(File::new).orElseGet(() -> new File(System.getProperty("java.io.tmpdir")));
   });
}
```

**Comment by WhiteCat22** [comment]
Thanks for the great feedback, I'll address it and update my PR tomorrow

**Comment by WhiteCat22** [comment]
I see I introduced a checkstyle error, I'll fix it tomorrow

**Review by jamezp — APPROVED** [review]

**Comment by WhiteCat22** [comment]
Thanks @jamezp

**Pull request merged**
