### PR TITLE
Support per-request idle timeout

### PR DESCRIPTION
**Pull request by dongxinEric**
(Not sure if this simple change needs a ticket so I directly opened the PR)

Right now a caller can set the request timeout on a per-request basis. This PR adds the similar ability for the idle timeout.

### CODE REVIEW

**Review by stevenschlansker — APPROVED** [review]

**Comment by stevenschlansker** [comment]
Hi @jamezp , sorry to bother you, but is there any chance this could be considered for the next Resteasy release? thanks!

**Comment by dongxinEric** [comment]
@jamezp Gentle ping. Is there a plan to include this change to a release scheduled?

**Comment by jamezp** [comment]
Sorry for the delay @dongxinEric. I won't be able to look at this until at least next week. I leave for PTO tomorrow and won't be back until Wednesday.

Currently I don't have a date set for a new release. I try to do one every quarter, but there aren't many changes/fixes in the current cycle. However, we could do one sometime in August for sure. Maybe middle of August so we can ensure to get some bug fixes it.

**Comment by dongxinEric** [comment]
> Sorry for the delay @dongxinEric. I won't be able to look at this until at least next week. I leave for PTO tomorrow and won't be back until Wednesday.
> 
> Currently I don't have a date set for a new release. I try to do one every quarter, but there aren't many changes/fixes in the current cycle. However, we could do one sometime in August for sure. Maybe middle of August so we can ensure to get some bug fixes it.

Thanks @jamezp !!

**Comment by jamezp** [comment]
@dongxinEric We require all contributions to be made under the terms of the ASL 2.0 License:[ http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0) 
Do you agree to these terms?

**Comment by dongxinEric** [comment]
> @dongxinEric We require all contributions to be made under the terms of the ASL 2.0 License:[ http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0) 
> 
> Do you agree to these terms?

Yes.

**Comment by dongxinEric** [comment]
@jamezp Sorry to bother you again on this PR, but I noticed this was not included into the [6.2.5 Final](https://github.com/resteasy/resteasy/releases/tag/6.2.5.Final) released last month. Do you know which release this patch will go into?

**Comment by jamezp** [comment]
@dongxinEric My apologies. I plan a 6.2.6.Final very soon, this week or next, and have it on my backport list.

**Pull request merged**
