### PR TITLE
[RESTEASY-1560] : Logging debug info for MessageBodyWriters and MessageBodyReaders

### PR DESCRIPTION
**Pull request by panossot**
[Resteasy 1560] : https://issues.jboss.org/browse/RESTEASY-1560
[Upstream] : https://github.com/resteasy/Resteasy/pull/1008

### CODE REVIEW

**Comment by asoldano** [comment]
@panossot , can you explain what differs among this PR and #1008 ? (RESTEASY-1560 vs RESTEASY-1558). Note next community release is going to be 3.1.0.Final, basically leaving 3.0.x branch for EAP maintenance.

**Comment by panossot** [comment]
@asoldano : There is no difference, just some printing naming changes according to @marekkopecky 's request (Interceptor to InterceptorWriter or InterceptorReader - https://github.com/resteasy/Resteasy/pull/1016/files#diff-ba3b6468b2d7f5a9ad7bd8e9db970ca7R60, https://github.com/resteasy/Resteasy/pull/1016/files#diff-1ef28f93771fb5440776bdec7018c1f3R128)

**Comment by marekkopecky** [comment]
In my point of view, it is necessary to have this in RESTEasy 3.0.x.

**Comment by marekkopecky** [comment]
Not sure, if it is necessary to have this in 3.0.x branch, but similar code is already merged in 3.0.x, see: https://github.com/resteasy/Resteasy/pull/951/files

**Comment by panossot** [comment]
It depends if it should be also included in 7.0.x

**Pull request merged**
