### PR TITLE
[RESTEASY-2684] Statically set provider factory on ResteasyClientBuilderImpl

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Anyone know if the following is a "known issue":

```
[ERROR] Failures: 
[ERROR]   ApacheHttpClient43Test.testConnectionCleanupProxy:144->testConnectionCleanupProxy:177 Wrong count of requests expected:<30> but was:<20>
```

Wouldn't expect the change I've made to affect that test

**Comment by ronsigal** [comment]
Hi @kenfinnigan,

I've been seeing that failure a lot lately. I haven't looked into what going wrong - maybe a timing issue? Anyway, I'll re-run the tests.

-Ron

**Comment by ronsigal** [comment]
I added a unit test.

**Comment by kenfinnigan** [comment]
Thanks @ronsigal, I'd been on PTO and wasn't able to follow up

**Pull request merged**
