### PR TITLE
RESTEASY-1434 Remove 'jaxrs' dir and move packages to top dir.

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
RESTEASY-1434

**Comment by ronsigal** [comment]
Hey Wei,

I've been working on deprecating some more stuff on the 3.0.x branch. 
I'll check it in tomorrow. Could you wait until I've done that before 
removing jaxrs?

Thanks,
Ron

On 07/05/2016 03:36 AM, Weinan Li wrote:
>
> Reopened #854 <https://github.com/resteasy/Resteasy/pull/854>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/resteasy/Resteasy/pull/854#event-712635557>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/AAg38ziwCpz7KymiDVkOipE3DAugofgQks5qSgl8gaJpZM4JEbSx>.
>

-- 
My company's smarter than your company (unless you work for Red Hat)

**Comment by liweinan** [comment]
@ronsigal sure.

**Comment by ronsigal** [comment]
Thanks, Weinan. I've just merged https://github.com/resteasy/Resteasy/pull/858, with 91 changed files. You saved me a headache. ;-)

**Comment by asoldano** [comment]
I'm closing this PR as I believe we really need to create a new one (due to conflicts, etc) if we still want to get rid of 'jaxrs' dir in 3.0.x and currently there does not seem to be a real need for that (the PR here is silent since ~2 months).

**Pull request closed without merging**
