### PR TITLE
initial setup for Github Action CI

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
It can coexist with existing Travis CI:

image

After github action side is fine-tuned(configured according to current travis ci setup), we can consider to remove travis-ci integration.

**Comment by ronsigal** [comment]
Hey @liweinan, have you seen PR https://github.com/resteasy/Resteasy/pull/2362? It looks like you and @jamezp are working on the same thing.

**Comment by jamezp** [comment]
My apologies. I should have asked the mailing list first, but it was just an experiment I was doing on Friday.

**Comment by ronsigal** [comment]
re: "My apologies"

Noooo!! Let a thousand flowers blossom. ;-)

**Comment by liweinan** [comment]
@ronsigal @jamezp  cool!  I guess we can close this one :-)

**Comment by liweinan** [comment]
work goes on here: https://github.com/resteasy/Resteasy/pull/2367

**Pull request closed without merging**
