### PR TITLE
Test BootableJar using Channel Manifest

### PR DESCRIPTION
**Pull request by tommaso-borgato**
This PR:
-  reintroduces bootable jar tests
- adds option to run bootable jar tests with a channel manifest

### CODE REVIEW

**Comment by liweinan** [comment]
The test failures seem to be related with the galleon update.

**Comment by tommaso-borgato** [comment]
@jbliznak can you have a look?

**Comment by liweinan** [comment]
I guess after @jamezp comes back he will check this.

**Comment by tommaso-borgato** [comment]
just rebased on main and have this error (in main too):
```shell
$ mvn clean install -DskipTests
...
[ERROR] Failed to execute goal on project resteasy-core-spi: Could not resolve dependencies for project org.jboss.resteasy:resteasy-core-spi:jar:7.0.0.Alpha2-SNAPSHOT: Failed to collect dependencies at jakarta.ws.rs:jakarta.ws.rs-api:jar:4.0.0: Failed to read artifact descriptor for jakarta.ws.rs:jakarta.ws.rs-api:jar:4.0.0: The following artifacts could not be resolved: jakarta.ws.rs:jakarta.ws.rs-api:pom:4.0.0 (absent): Could not transfer artifact jakarta.ws.rs:jakarta.ws.rs-api:pom:4.0.0 from/to central-libs-release (https://repository.eapqe.psi.redhat.com:8081/artifactory/libs-release): Unsupported or unrecognized SSL message -> [Help 1]
```

**Comment by tommaso-borgato** [comment]
just re-base on main and with both main and this branch I get:

```
$ mvn clean install -DskipTests
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< org.jboss.resteasy:resteasy-core-spi >----------------
[INFO] Building RESTEasy Core SPI 7.0.0.Alpha2-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central-libs-release: https://repository.eapqe.psi.redhat.com:8081/artifactory/libs-release/jakarta/ws/rs/jakarta.ws.rs-api/4.0.0/jakarta.ws.rs-api-4.0.0.pom
Downloading from libs-snapshot: https://repository.eapqe.psi.redhat.com:8081/artifactory/libs-snapshot/jakarta/ws/rs/jakarta.ws.rs-api/4.0.0/jakarta.ws.rs-api-4.0.0.pom
Downloading from artifactory: https://repository.eapqe.psi.redhat.com:8081/artifactory/all/jakarta/ws/rs/jakarta.ws.rs-api/4.0.0/jakarta.ws.rs-api-4.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.514 s
[INFO] Finished at: 2024-04-15T10:49:49+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project resteasy-core-spi: Could not resolve dependencies for project org.jboss.resteasy:resteasy-core-spi:jar:7.0.0.Alpha2-SNAPSHOT: Failed to collect dependencies at jakarta.ws.rs:jakarta.ws.rs-api:jar:4.0.0: Failed to read artifact descriptor for jakarta.ws.rs:jakarta.ws.rs-api:jar:4.0.0: The following artifacts could not be resolved: jakarta.ws.rs:jakarta.ws.rs-api:pom:4.0.0 (absent): Could not transfer artifact jakarta.ws.rs:jakarta.ws.rs-api:pom:4.0.0 from/to central-libs-release (https://repository.eapqe.psi.redhat.com:8081/artifactory/libs-release): Unsupported or unrecognized SSL message -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

**Comment by jamezp** [comment]
We can talk offline about this, but I need to understand the motivation behind this. I've got some opinions on how we test the bootable JAR that I might share alone, but I don't think we do it right :)

**Comment by jamezp** [comment]
Just an FYI I left a review on #4108, but that would apply here too. For now we could focus on one PR so you don't have to keep updating both and cherry-pick it after we're satisfied. I'm happy to handle the cherry-pick as well.

**Pull request merged**
