### PR TITLE
[RESTEASY-1703] added subsection in upgrade guide

### PR DESCRIPTION
**Pull request by rsearls**
Test revised based upon coding feedback on PR for RESTEASY-1712

### CODE REVIEW

**Comment by rsearls** [comment]
@ronsigal, I revised the text based upon your previous comments.  Would you review this explanation for clarity and correctness?

**Comment by ronsigal** [comment]
@rsearls, it makes a lot more sense to me now. I removed a few commas because I'm obsessive that way. ;-)

**Comment by ronsigal** [comment]
Well, damn, my changes created a conflict. This page says "Use the web editor ... to resolve conflicts." but I don't know how to do that. :((

**Comment by ronsigal** [comment]
Ok, you click on "web editor", make the changes, and click on "Mark as Resolved" in the editor.

I removed two more commas. We're up to 4 commits now. ;-)

**Comment by rsearls** [comment]
@ronsigal, thanks

**Pull request merged**
