### PR TITLE
[RESTEASY-1533] Public/private module separation

### PR DESCRIPTION
**Pull request by asoldano**
This PR provides a proposal for defining a public spi for the current resteasy-jaxrs and resteasy-client modules. This is a requirement for clearly stating what we guarantee to be stable and only possibly changing in major releases, versus what might changes in minor and micros too. Proper user expectations, easier project evolution and maintenance.

### resteasy-jaxrs
This is now split into **resteasy-jaxrs** and **resteasy-jaxrs-impl**. The former includes the following packages:

- org.jboss.resteasy.annotations
- org.jboss.resteasy.api.validation
- org.jboss.resteasy.spi
- org.jboss.resteasy.plugins.providers.validation 

The latter includes:

- org.jboss.resteasy.core
- org.jboss.resteasy.mock
- org.jboss.resteasy.plugins
- org.jboss.resteasy.specimpl
- org.jboss.resteasy.tracing
- org.jboss.resteasy.util

### resteasy-client
This is now split into **resteasy-client** and **resteasy-jaxrs-client-api** . The latter only includes the following classes that are used for configuring the RESTEasy client additions:

- ClientHttpEngine & ClientHttpEngineBuilder
- ProxyBuilder & ProxyConfig
- ResteasyClient
- ResteasyClientBuilder
- ResteasyWebTarget

### JBoss Modules
There's a new _org.jboss.resteasy.resteasy-jaxrs-public_ module including resteasy-jaxrs and resteasy-jaxrs-client-api. The already existing _org.jboss.resteasy.resteasy-jaxrs_ as well as all other _org.jboss.resteasy.*_ modules should become private.

### Non backward compatible changes
Clearly, the refactoring comes with some unavoidable class moves and changes that imply breaking backward comaptibility (this is the reason why this only fits master). I tried to avoid breaking anything as much as possible, but sometimes there's no way (we also have to avoid splitting packages because of JDK 9 changes).

- Some classes have been moved from package _org.jboss.resteasy.util_ to package _org.jboss.resteasy.spi.util_: **Types**, **FindAnnotation**, **MethodHashing** and **PickConstructor**.
- Some classes have been moved from package _org.jboss.resteasy.spi.touri_ to package _org.jboss.resteasy.plugins.touri_: *AbstractURITemplateAnnotationReader**, **MappedByAnnotationReader**, **ObjectToURI**, **URITemplateAnnotationReader** and **URIableURIResolver**.
- **HTTPResponseCodes** has moved from package _org.jboss.resteasy.util_ to package _org.jboss.resteasy.spi_.
- **ResponseInvoker** has moved from package _org.jboss.resteasy.core_ to package _org.jboss.resteasy.spi_ and has broader request and response types on  _invoke(..)_ methods.
- The _getMethod_ and _setMethod_ methods of **ResteasyAsynchronousResponse**  have been factored out to new _org.jboss.resteasy.core.ResourceMethodInvokerAwareResponse_.
- **InternalDispatcher** has moved from pachage _org,jboss.resteasy.spi_ to package _org.jboss.resteasy.core_.
- **ValueInjector** and **Dispatcher** have moved from pachage _org,jboss.resteasy.core_ to package _org.jboss.resteasy.spi_.
- **org.jboss.resteasy.spi.LinkHeaders** has been removed.
- ResteasyUriInfo has moved from package _org.jboss.resteasy.spi_ to package _org.jboss.resteasy.specimpl_.
- **org.jboss.resteasy.spi.ResteasyDeployment** has turned into an interface with the same methods it previously had; it's now implemented by **org.jboss.resteasy.core.ResteasyDeploymentImpl**
- **org.jboss.resteasy.spi.ProviderFactory** is now an abstract class; all non-static methods are not abstract and implemented in **org.jboss.resteasy.core.ResteasyProviderFactoryImpl**.
- **JaxrsInterceptorRegistry** and **JaxrsInterceptorRegistryListener** have moved from package _org.jboss.resteasy.core.interception.jaxrs_ to package _org.jboss.resteasy.spi.interception_; the former is also turned into an interface with the same method it had before; it's implemented by *JaxrsInterceptorRegistryImpl* in package _org.jboss.resteasy.core.interception.jaxrs_.
- **ClientRequestFilterRegistry**, **ClientResponseFilterRegistry**, **ContainerRequestFilterRegistry**, **ContainerResponseFilterRegistry**, **ReaderInterceptorRegistry** and **WriterInterceptorRegistry** in package _org.jboss.resteasy.core.interception.jaxrs_ have been renamed to **ClientRequestFilterRegistryImpl**, **ClientResponseFilterRegistryImpl**, **ContainerRequestFilterRegistryImpl**, **ContainerResponseFilterRegistryImpl**, **ReaderInterceptorRegistryImpl** and **WriterInterceptorRegistryImpl** respectively, same package.
- **ResteasyUriBuilder** has moved from package _org.jboss.resteasy.specimpl_ to package _org.jboss.resteasy.spi_ and is now abstract; it's extended by non-abstract class **org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl**.
- **org.jboss.resteasy.client.jaxrs.ProxyBuilder** is now abstract; it's extended by non-abstract class **org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl**.
- Some classes have been moved from package _org.jboss.resteasy.client.jaxrs_ to package _org.jboss.resteasy.client.jaxrs.engines_: **AsyncClientHttpEngine**, **ClientHttpEngineBuilder43**, **VerifierWrapper* and **BasicAuthentication**.
- **org.jboss.resteasy.client.jaxrs.ResteasyClient** is now abstract, witth all non static methods as abstract ones; it's extended by non-abstract class **org.jboss.resteasy.client.jaxrs.internal.ResteasyClientImpl**.
- **org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder** is now abstract, witth all non static methods as abstract ones; it's extended by non-abstract class **org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl**.
- **ViolationsContainer** has been removed
- **ConstraintTypeUtil11** has moved from package _org.jboss.resteasy.plugins.providers.validation_ to package _org.jboss.resteasy.plugins.validation_.
- **ConstraintTypeUtil** has moved from package _org.jboss.resteasy.plugins.providers.validation_ to package _org.jboss.resteasy.spi.validation_.
- **ResteasyViolationException** is not abstract and extended by **ResteasyViolationExceptionImpl**

### CODE REVIEW

**Comment by marekkopecky** [comment]
Module naming is a little bit inconsistent:
API: resteasy-jaxrs, resteasy-jaxrs-client-api
IMPL: resteasy-jaxrs-impl, resteasy-client

Jax-rs api doesn't have a suffix (-api), but client api has a suffix (-api). Jax-rs impl has a suffix (-impl), but client impl doesn't have a suffix (-impl).

What about make some naming convention, like "resteasy-jaxrs, resteasy-jaxrs-impl, resteasy-client, resteasy-client-impl", or "resteasy-jaxrs-api, resteasy-jaxrs, resteasy-client-api, resteasy-client", or something similar? WDYT?

**Comment by marekkopecky** [comment]
What about to add more `final` keyword to API classes? Like `CorsHeaders`, `ConstraintTypeUtil11`, etc?

**Comment by marekkopecky** [comment]
If you have a time ... you can also check checkstyle, current master should be aligned with this checkstyle.xml: https://issues.jboss.org/browse/RESTEASY-1974?focusedCommentId=13610933&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13610933
(this checkstyle file contains just subset of rules from checkstyle in resteasy repo)

**Comment by asoldano** [comment]
> Module naming is a little bit inconsistent:
> API: resteasy-jaxrs, resteasy-jaxrs-client-api
> IMPL: resteasy-jaxrs-impl, resteasy-client
> 
> Jax-rs api doesn't have a suffix (-api), but client api has a suffix (-api). Jax-rs impl has a suffix (-impl), but client impl doesn't have a suffix (-impl).
> 
> What about make some naming convention, like "resteasy-jaxrs, resteasy-jaxrs-impl, resteasy-client, resteasy-client-impl", or "resteasy-jaxrs-api, resteasy-jaxrs, resteasy-client-api, resteasy-client", or something similar? WDYT?

I've been thinking about this; resteasy-jaxrs is not really an api, though, while resteasy-jaxrs-client-api is.
If we want to keep an easy upgrade path, we can do:

- resteasy-jaxrs-spi
- resteasy-jaxrs
- resteasy-client-api
- resteasy-client

Otherwise a better naming could be:

- resteasy-core-spi
- resteasy-core
- resteasy-client-api
- resteasy-client

... dropping the _jaxrs_ which is kind of assumed. WDYT?

**Comment by rsearls** [comment]
This restructuring looks good to me.  
You are the new record holder for number of files changed in a single commit.

**Comment by ronsigal** [comment]
There's a lot to absorb. Now THIS is "epic". ;-)

One point, for now: Seeing org.jboss.resteasy.plugins.providers.validation in public was a little jarring, and I think it can be done away with. As for ConstraintTypeUtil and ConstraintTypeUtil11, once upon a time there were two versions of the Resteasy validation layer, resteasy-validator-provider-11 for Hibernate Validator 5 (Bean Validation 1.1) and another one for Hibernate Validator 4 (Bean Validation 1.0). That's why there were two versions of ConstraintTypeUtil. Now that the BV 1.0 module is gone, I think it would be safe to move ConstraintTypeUtil and ConstraintTypeUtil11 to the resteasy-validator-provider-11 module. Also, it looks like ViolationsContainer, which is used only by two org.jboss.resteasy.api.validation.ResteasyViolationException (resteasy-jaxrs) constructors, can be removed since those constructors are no longer called.

Alessio, I can make these changes in a separate pull request, or you can just make them here. 

-Ron

**Comment by asoldano** [comment]
@ronsigal thanks Ron, I agree on your proposals. I'm basically off for today, so if you still have some time, feel free to create a commit on top of mine and I'll cherry-pick it here. Otherwise we can work on this next week.

**Comment by ronsigal** [comment]
@asoldano, I've created https://github.com/resteasy/Resteasy/pull/1698 with the validation changes. The reason there are validation classes in resteasy-jaxrs was, as I mentioned before, that there used to be two different implementations of validation. I was thinking of moving everything into resteasy-validator-provider-11, but I see that there is now CDI 2.0. I guess, in principle, that we could have a new validation module based on CDI 2.0, so maybe it makes sense to leave things spread out, with API and SPI classes in resteasy-jaxrs.

-Ron

**Comment by asoldano** [comment]
Thanks @ronsigal , I've cherry-picked the last commit from your PR :+1:

**Comment by marekkopecky** [comment]
I check quickstarts and grep TS logs for "Deployment * is using a private module". I don't find anything relevant, just this one:
```
testsuite/integration-tests/target/surefire-reports/null-output.txt:10:03:49,003 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-6) WFLYSRV0018: Deployment "deployment.war_with_jsonb.war" is using a private module ("org.jboss.resteasy.resteasy-json-binding-provider") which may be changed or removed in future versions without notice.
```

But this message is printed in current master as well, so it is not relevant with current PR.

**Comment by asoldano** [comment]
I've added another commit that moves the contextual data management out of the ResteasyProviderFactory (almost all static methods except for the get/newInstance) to a dedicated ResteasyContext class, out of the SPI. That also allows removing the ThreadLocalStack class from the SPI too. Perhaps there's much that could now be turned into "private" in the ResteasyProviderFactory interface and move out of the SPI...

**Comment by asoldano** [comment]
@marekkopecky , do you know/have you checked if that warning is printed only when the module dependency is explicitly set by the user? (versus automatically added by wildfly jaxrs integration)

**Comment by asoldano** [comment]
Having heard no further opinions on the module naming topic, I've renamed resteasy-jaxrs -> resteasy-core-spi, resteasy-jaxrs-impl -> resteasy-core, resteasy-jaxrs-client-api -> resteasy-client-api.

At this point, I'm planning to leave this PR here for review for a couple of days, so that it can be reviewed, please let me know.

**Comment by asoldano** [comment]
Rebased to fix conflicts..

**Comment by marekkopecky** [comment]
@asoldano warning is printed only when some class from private module is used in deployment code ...

**Pull request merged**
