### PR TITLE
fixing issue with proxybuild

### PR DESCRIPTION
**Pull request by ChrisL113**
Hi I just recently had an issue with this package I would like that you take a look at my changes since this is the solution for this comeup error 
image

### CODE REVIEW

**Comment by ChrisL113** [comment]
i'm running the latest image of keycloak, here https://hub.docker.com/r/jboss/keycloak/

**Comment by jamezp** [comment]
Do you by any chance have an example deployment? I would need to see what's happening. However, we really need to default to the TCCL. Given the `KeycloakConnectionService` in that stack trace, it might be possible to setup the TCCL (`Thread.currentThread().setContextClassLoader()`).

**Comment by ChrisL113** [comment]
I will ask to my team tomorrow and i will get back to you

**Comment by ChrisL113** [comment]
here there are some things I changed tho
image

**Comment by ChrisL113** [comment]
hello ? ?????

**Comment by jamezp** [comment]
Sorry, I was on PTO. I'd like to understand how to reproduce the issue here, but I'm not sure how to do that. We can't do the change as that will break how RESTEasy works in containers like WildFly.

**Comment by jamezp** [comment]
I'm closing this as we need to use the TCCL in most containers. If this is still an issue, please feel free to file an issue on [JIRA](https://issues.redhat.com/browse/RESTEASY) with some details on how to reproduce the issue. Thank you for your patience on this overdue PR.

**Pull request closed without merging**
