### PR TITLE
Fix scaning rest path annotated classes-exclude interfaces

### PR DESCRIPTION
**Pull request by pgozdzikowski**
My problem was that when I wanted to use in same application rest easy client proxy and rest controllers then I got exception that there is absent no-args public constructor. This fix solved my issue.

### CODE REVIEW

**Comment by ronsigal** [comment]
Hi pgozdzikowski,

Can you create a JIRA issue at https://jira.jboss.org/browse/RESTEASY so we can discuss further.?

What exactly did the exception look like? I'd like to see where it's coming from.

Thanks,
Ron

**Comment by pgozdzikowski** [comment]
https://issues.jboss.org/browse/RESTEASY-1189
Done.

**Comment by ronsigal** [comment]
Thanks. I'll continue the discussion at the JIRA issue.

**Comment by asoldano** [comment]
Closing as per comment on JIRA.

**Pull request closed without merging**
