### PR TITLE
[RESTEASY-3134] Do not cause a NPE when source is not available

### PR DESCRIPTION
**Pull request by tobiasstadler**
https://issues.redhat.com/browse/RESTEASY-3134

Signed-off-by: Tobias Stadler <ts.stadler@gmx.de>

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@jamezp Would you please have a look?

**Comment by jamezp** [comment]
4.x PR #3100

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
These CI failures don't really have anything to do with this PR.

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by tobiasstadler** [comment]
@jamezp Do you think this fix can make it into the next JBoss EAP 7.4 release?

**Pull request merged**
