### PR TITLE
[RESTEASY-2996] Calling send for each chunk with flush and completing the future

### PR DESCRIPTION
**Pull request by dnagarajan89**
I cherry picked this change from the main branch as we need this change back ported to the last release version. 

Main [PR](https://github.com/resteasy/resteasy/pull/2882).

### CODE REVIEW

**Review by jamezp — APPROVED** [review]

**Comment by dnagarajan89** [comment]
@jamezp  We are looking forward to make use of this fix as well as [this one](https://github.com/resteasy/resteasy/commit/a8e8042ea3b16096163141d1212ff229baf75a6b) which was recently merged to 4.7. Can you help make a 4.7 patch release with these fixes ?

**Comment by jamezp** [comment]
> @jamezp We are looking forward to make use of this fix as well as [this one](https://github.com/resteasy/resteasy/commit/a8e8042ea3b16096163141d1212ff229baf75a6b) which was recently merged to 4.7. Can you help make a 4.7 patch release with these fixes ?

@dnagarajan89 Yes. I'll include this in the 4.7.2.Final release as well.

**Comment by dnagarajan89** [comment]
> > @jamezp We are looking forward to make use of this fix as well as [this one](https://github.com/resteasy/resteasy/commit/a8e8042ea3b16096163141d1212ff229baf75a6b) which was recently merged to 4.7. Can you help make a 4.7 patch release with these fixes ?
> 
> @dnagarajan89 Yes. I'll include this in the 4.7.2.Final release as well.

@jamezp is there a tentative date for the release so that we can plan accordingly ?

**Comment by jamezp** [comment]
> @jamezp is there a tentative date for the release so that we can plan accordingly ?

I'm planning on today or tomorrow. One other possible bug has been found in WildFly we need to sort out, then I'll release. At the very latest sometime next week as there is a WildFly release planned then and we need any bug fixes in.

**Comment by jamezp** [comment]
@dnagarajan89 I guess the day was today. 4.7.2.Final has been released.

**Comment by dnagarajan89** [comment]
> @dnagarajan89 I guess the day was today. 4.7.2.Final has been released.

@jamezp Great news!. Thanks a lot for your kind help and support.

**Pull request merged**
