### PR TITLE
[RESTEASY-2226]:NullPointerException in PatchMethodFilter

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Comment by ronsigal** [comment]
Hey @jimma,

I've noticed lately that I can't restart travis tests any more. Do you know anything abou that?

-Ron

**Comment by jimma** [comment]
@ronsigal  Same here. Looks we are not in the admin list. I checked the repo under my id can be triggered.
@asoldano Can you restart the travis build ?

**Comment by asoldano** [comment]
@jimma @ronsigal , I've restarted the builds. However this is strange, you both have admin rights on the repo and that is what should control this. Please let me know if you have same issues in different PRs.

**Comment by jimma** [comment]
@asoldano  Another PR  doesn't work either : https://github.com/resteasy/Resteasy/pull/2354

**Comment by ronsigal** [comment]
@asoldano, yeah, I had the same problem on another PR, early last week, I think. Probably was https://github.com/resteasy/Resteasy/pull/2340.

**Comment by jimma** [comment]
Looks like travis bug : https://travis-ci.community/t/job-restart-button-are-not-always-appearing-on-build-page/5811/17

**Comment by ronsigal** [comment]
re: "travis bug"

Ahhhhh!!!

**Pull request merged**
