### PR TITLE
RESTEASY-1774 - Upgrade HTTP client to 4.5.4

### PR DESCRIPTION
**Pull request by rpelisse**
Issue: https://issues.jboss.org/browse/RESTEASY-1774
Upstream Issue: https://issues.jboss.org/browse/WFCORE-3473
EAP Issue: https://issues.jboss.org/browse/JBEAP-13801

### CODE REVIEW

**Comment by rpelisse** [comment]
@asoldano On my machine, the RestEasy test suite also fails in the same place (integration-tests) - even before I applied my change (so the upgrade HTTP). Is it a known issue of the current content of master ? Or should I / can I do something about it ?

**Comment by asoldano** [comment]
@rpelisse , I would think the failures are related to the changes; the testsuite is passing with the master here. Which test is actually failing there in the integration-tests module ? Is it the same as here (AsyncTimeoutExceptionTest) ?

**Comment by asoldano** [comment]
@rpelisse I confirm that the changes cause a regression in that test, verified locally :-(

**Comment by rpelisse** [comment]
OK, so i'll ignore for now the other tests failing for me for now, and try to investigate why this one especially is being affected by this upgrade... Thanks for checking that!

**Comment by rpelisse** [comment]
OK, seems that the update have change some internal timeout in the http client. The following changes allow the test to pass:

```
diff --git a/testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncTimeoutExceptionsTest.java b/testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncTimeoutExceptionsTest.java
index 78962d40d..814479bac 100644
--- a/testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncTimeoutExceptionsTest.java
+++ b/testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AsyncTimeoutExceptionsTest.java
@@ -190,7 +190,7 @@ public class AsyncTimeoutExceptionsTest extends ClientTestBase{
         Future<Response> future = base.request().async().get();
         Response response = null;
         try {
-            response = future.get(5, TimeUnit.SECONDS);
+            response = future.get(1, TimeUnit.SECONDS);
         } catch (TimeoutException ex) {
             Assert.assertEquals(TimeoutException.class.getName(), ex.toString());
         }
@@ -284,7 +284,7 @@ public class AsyncTimeoutExceptionsTest extends ClientTestBase{
         Future<Response> future = base.request().async().get(new ResponseCallback());
         Response response = null;
         try {
-            response = future.get(5, TimeUnit.SECONDS);
+            response = future.get(1, TimeUnit.SECONDS);
         } catch (TimeoutException ex) {
             Assert.assertEquals(TimeoutException.class.getName(), ex.toString());
         }
```

Do you want me to explore and see if I can find which timeout has been tweaked and maybe switch back to the previous value for this test ? Or do you think that modify the test as above makes (more) sense ?

**Comment by asoldano** [comment]
@rpelisse thanks for the investigation so far. Generally speaking, there's no rule absolutely preventing changing the test, though it would be good to know what has changed, as we might want to mention that in the release notes..
Thanks

**Comment by rpelisse** [comment]
@asoldano FYI, I've track down the [commit in httpclient](https://github.com/apache/httpcomponents-client/commit/5a9a842d23b520a19ff7011059fe54279e2446c4) causing this test to fails - is this enough to refers to in the release note ? Do you think we should tweak more the test or simply modify our test ? 

I've updated this PR to include the modify test, but please let me know if you prefer do take care of this differently!

**Comment by rpelisse** [comment]
Hum, weird... not sure what it is failing here. I did not run into that locally...

**Comment by rpelisse** [comment]
@asoldano Alessio, just to be sure, i've double check locally on building 4 times the failing test, but still no error:

```
$ for i in {1..4} ; do mvn clean install ; done | grep -e 'Tests run: ' -e 'BUILD ' 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.644 s - in org.jboss.resteasy.test.HeadContentLengthTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.088 s - in org.jboss.resteasy.test.HttpContextTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 s - in org.jboss.resteasy.test.PortAssigningTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.331 s - in org.jboss.resteasy.test.security.BasicAuthTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0
[INFO] BUILD SUCCESS
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.599 s - in org.jboss.resteasy.test.HeadContentLengthTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.131 s - in org.jboss.resteasy.test.HttpContextTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in org.jboss.resteasy.test.PortAssigningTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.329 s - in org.jboss.resteasy.test.security.BasicAuthTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0
[INFO] BUILD SUCCESS
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.688 s - in org.jboss.resteasy.test.HeadContentLengthTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.16 s - in org.jboss.resteasy.test.HttpContextTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.jboss.resteasy.test.PortAssigningTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.334 s - in org.jboss.resteasy.test.security.BasicAuthTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0
[INFO] BUILD SUCCESS
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.704 s - in org.jboss.resteasy.test.HeadContentLengthTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.158 s - in org.jboss.resteasy.test.HttpContextTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.jboss.resteasy.test.PortAssigningTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.321 s - in org.jboss.resteasy.test.security.BasicAuthTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0
[INFO] BUILD SUCCESS
```

Do you have any idea on how I could investigate this more ?

**Comment by asoldano** [comment]
@rpelisse , I'm leaning towards fixing the test affected by the upgrade in a different way; can you check https://github.com/resteasy/Resteasy/pull/1415 and tell me what you think? Basically, in there we're trying calling a resource methods that lasts 10s and want to timeout after 5s of wait. However, the socket timeout is now being effectively set to 2s, so we get a read time out instead of the future timeout. You change would make the test faster, but I think we might have problems from time to time on slow environments, like the Travis CI here. So keeping the longer timeout is probably safer.
If you agree I would close this PR and merge the new one. Please let me know.

**Comment by rpelisse** [comment]
@asoldano I think your way is way better! I've +1 your PR and I'm closing this one :)

**Pull request closed without merging**
