### PR TITLE
Resteasy async client

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
Still not finished yet, put it here to record the progress and for reference.

**Comment by liweinan** [comment]
SpecialResourceTest.test583() failed because of httpcomponents minor version update (It uses stricter mime type checking, so the test need to be rewritten. Currently it is ignored)

**Comment by liweinan** [comment]
AsyncTimeoutExceptionsTest.futureTimeoutAndMoreRequestsTest() won't timeout when async client is used.

**Comment by liweinan** [comment]
AsyncTimeoutExceptionsTest .invocationCallbackTimeoutAndMoreRequestsTest() won't timeout when async client is enabled.

**Comment by liweinan** [comment]
Current progress:

- Migrated Markus PR
- Made async-client fully optional (When async-client is in classpath, it will be used, or else it will fallback to the existing asyncExecutor)
- legacy-tests test with out async-client
- non legacy integration tests are tested with async-client now

**Comment by ronsigal** [comment]
This is pretty cool stuff. I've written a test that uses the NIO client, and it seems to be kinda long:
```
   @Test
   public void testNIO() throws Exception {
      HttpAsyncClientBuilder asyncClientBuilder = HttpAsyncClientBuilder.create();
      CloseableHttpAsyncClient httpAsyncClient = asyncClientBuilder.build();
      ClientHttpEngine engine = new ApacheHttpAsyncClient4Engine(httpAsyncClient, true);
      ResteasyClientBuilder clientBuilder = new ResteasyClientBuilder();
      clientBuilder.httpEngine(engine);
      Client client = clientBuilder.build();
      WebTarget target = client.target("http://localhost:8081/test");
      Builder builder = target.request();
      AsyncInvoker asyncInvoker = builder.async();
      Future<Response> future = asyncInvoker.get();
      Response response = future.get();
      String report = response.readEntity(String.class);
      System.out.println("response: " + report);
      client.close();
   }
```
Obviously, I'm not taking advantage of the fluent API, which was just for my own understanding, but building the Client takes a lot of work. Is there an easier way?

-Ron

**Comment by ronsigal** [comment]
How about something like ResteasyClientBuilder.buildAsync() that creates an ApacheHttpAsyncClient4Engine?

**Comment by asoldano** [comment]
I'm working on this at https://github.com/resteasy/Resteasy/pull/1249 ...

**Pull request closed without merging**
