### PR TITLE
Allow sub-resouce locators to return class

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Comment by liweinan** [comment]
Your PR is based on my thoughts and code: https://github.com/resteasy/Resteasy/pull/1188

Could you please create the PR based on my branch?

To achieve this, you can pull my branch `support-sublocator-class-injection` and add the additional tests on top of the commit.

Thanks!

**Comment by jimma** [comment]
> Your PR is based on my thoughts and code: #1188

How come it is based on your thoughts and code. I think your thoughts and code to do injection is not correct. That's why I create this PR. 

> Could you please create the PR based on my branch?
To achieve this, you can pull my branch support-sublocator-class-injection and add the additional tests on top of the commit.

I don't think it's necessary.  Your test isn't testing the purpose of adding return class support.

**Comment by liweinan** [comment]
Your PR obviously copies my idea in ResourceLocatorInvoker.java with minor modifications. Other parts are some additional tests. I have spent a week on this issue with many discussions with team and finally find the correct place to add the feature. Please, at least, learn to respect other's work. Thanks.

**Comment by jimma** [comment]
> Your PR obviously copies my idea in ResourceLocatorInvoker.java with minor modifications.
 Other parts are some additional tests. I have spent a week on this issue with many discussions with team and finally find the correct place to add the feature. Please, at least, learn to respect other's work. Thanks

I am surprised that you said this. Before you make this statement, did you look at my change and test carefully ?  You don't do this correctly and I get this fixed with another PR. Sorry , I can't fix this based on your wrong thing.   
Another one change this place is a copy of your work and  it doesn't respect  your work.  I really doubt it.

**Comment by asoldano** [comment]
Superseded by https://github.com/resteasy/Resteasy/pull/1193

**Pull request closed without merging**
