### PR TITLE
[RESTEASY-1761] Limit size of SelfExpandingBufferedInputStream

### PR DESCRIPTION
**Pull request by asoldano**

### CODE REVIEW

**Comment by asoldano** [comment]
This is a followup of https://github.com/resteasy/Resteasy/pull/1350

**Comment by juddmei** [comment]
BTW, I think it is better to add some comments to doc so as to reminder the developers this class only support a stream that has size smaller than 1GB. What do you think?

**Comment by asoldano** [comment]
@juddmei , it would make sense. Where (which section) in the doc would you add this piece of information?

**Comment by juddmei** [comment]
How about add it to the Java Doc of the class?

**Pull request merged**
