### PR TITLE
[RESTEASY-2189] port of RESTEASY-1364 and RESTEASY-2177 changes to 3.7

### PR DESCRIPTION
**Pull request by rsearls**

### CODE REVIEW

**Comment by asoldano** [comment]
I'm setting the "Do not merge label" for the reason explained at https://issues.jboss.org/browse/RESTEASY-2187?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=13710503#comment-13710503

**Comment by asoldano** [comment]
@rsearls , I've removed the Do Not Merge label. Please be sure to include the fix for RESTEASY-2187 here too. Thanks!

**Comment by rsearls** [comment]
Two tests, ResourceInfoInjectionTest and FormParamTest have been adjusted in 
accordance with the requirements of [RESTEASY-1364].  These same 2 adjustments 
are present in Master.  3.7 is in alignment with master.  I have made Ron's 
logging change here as well.

**Comment by asoldano** [comment]
Thanks!

**Pull request merged**
