### PR TITLE
[RESTEASY-1357] [RESTEASY-1200][RESTEASY-975] upgraded to Apache 4.3 …

### PR DESCRIPTION
**Pull request by rsearls**
…APIs. Retained resteasy classes to continue support for pre-4.3 apis. Arquillian wfly-10 tests added

### CODE REVIEW

**Comment by asoldano** [comment]
@rsearls looks like Travis is failing, can you have a look and fix the problem? Thanks

**Comment by rsearls** [comment]
Branch fixed.   Travis runs successfully.

**Comment by asoldano** [comment]
Merged, thanks Rebecca. Btw, what was the reason for the failure before?

**Comment by rsearls** [comment]
An import changed with an archive version change

**Pull request merged**
