### PR TITLE
[RESTEASY-1709]

### PR DESCRIPTION
**Pull request by ronsigal**
Create proxy for injected Application.

### CODE REVIEW

**Comment by asoldano** [comment]
@ronsigal , is this PR still needed? If not, please close it, so that we cleanup the PR list a bit. Thanks!

**Comment by asoldano** [comment]
@ronsigal , if it's needed, instead, does the "Do not merge" label still apply, or we can consider/review it and possibly merge?

**Comment by asoldano** [comment]
ok, I'm closing this, it can be reopened if needed.

**Comment by ronsigal** [comment]
@asoldano, sorry, I missed this. The issue is still open and pretty thorny, as I recall. I'll try to get back to it.

**Pull request closed without merging**
