### PR TITLE
master

### PR DESCRIPTION
**Pull request by cwiejack**
add helper method to identify all declared methods on a class. 
This will fix loading problems with Spring 4.2.1

### CODE REVIEW

**Comment by choweiyuan** [comment]
Would this fix https://issues.jboss.org/browse/RESTEASY-1221??

**Comment by cwiejack** [comment]
Hi,
actually I do not know.
This is a fix for  in the SpringBeanProcessor to avoid the following exception:
```java
Exception in thread "main" java.lang.IllegalStateException: RESTEASY013015: could not find the type for bean named org.springframework.transaction.config.internalTransactionalEventListenerFactory
	at org.jboss.resteasy.plugins.spring.SpringBeanProcessor.getBeanClass(SpringBeanProcessor.java:457)
	at org.jboss.resteasy.plugins.spring.SpringBeanProcessor.processBean(SpringBeanProcessor.java:282)
	at org.jboss.resteasy.plugins.spring.SpringBeanProcessor.postProcessBeanFactory(SpringBeanProcessor.java:260)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:174)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:673)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
```
After commiting the pull request I saw that there already was a fix (see https://github.com/resteasy/Resteasy/pull/659)

**Comment by pdishchekenian** [comment]
cwiejack: your fix for issue in SpringBeanProcessor is much appreciated! I introduced your snapshot into my project and problem was resolved. 

To the resteasy team, when can I expect the changes be merged into resteasy:master? Hopefully it will be available with 3.0.14.Final?

Thanks,
Pete

**Comment by andreysaksonov** [comment]
guys, please merge this ASAP, our project suffers from this issue

**Comment by liweinan** [comment]
Thanks for all hands :-) As PR695 is merged I'll close this one.

**Pull request closed without merging**
