### PR TITLE
[RESTEASY-2239] updated mime4j to version 0.8.2

### PR DESCRIPTION
**Pull request by rsearls**

### CODE REVIEW

**Comment by rsearls** [comment]
Change complete

**Comment by rakeshk15** [comment]
seems this fix didn't make it to v4.5.4

Below issue has mentioned the fix version as 4.5.4

https://issues.redhat.com/browse/RESTEASY-2239 

Please clarify.

**Comment by asoldano** [comment]
Please download / try 4.5.5.Final, which should have the fix.

**Comment by rakeshk15** [comment]
thanks @asoldano, v4.5.5 works fine.

**Pull request merged**
