### PR TITLE
[RESTEASY-2872] Multipart annotation ignored when using async rest client

### PR DESCRIPTION
**Pull request by spbolton**
https://issues.redhat.com/browse/RESTEASY-2872

### CODE REVIEW

**Comment by jamezp** [comment]
We require all contributions to be made under the terms of the ASL 2.0 License: http://www.apache.org/licenses/LICENSE-2.0 
Do you agree to these terms?

**Comment by spbolton** [comment]
> We require all contributions to be made under the terms of the ASL 2.0 License: http://www.apache.org/licenses/LICENSE-2.0
> Do you agree to these terms?
Yes

**Comment by jamezp** [comment]
These failures don't seem relevant to this PR. I'm testing a surefire upgrade on #2762 to see if it works. Hopefully that will make these issues go away.

**Comment by spbolton** [comment]
@jamezp I agree, looks like the failures were due to the surefire changes.   Will someone need to manually kick this off again when that is resolved?

**Review by jamezp — APPROVED** [review]

**Pull request merged**
