### PR TITLE
[RESTEASY-2843] Do not add the target type to the thrown exception. I…

### PR DESCRIPTION
**Pull request by jamezp**
…nstead log it as a debug message.

https://issues.redhat.com/browse/RESTEASY-2843

Upstream: #2741

### CODE REVIEW

**Comment by fgrilli** [comment]
Hello, any chance you could release this version anytime soon? This is apparently deemed as a security issue one of my company's projects depends upon. Thank you.

**Comment by jamezp** [comment]
@fgrilli We can likely do this. Do you have a container you target?

**Comment by fgrilli** [comment]
@jamezp thank you! Do you mean a servlet container? If so, that would be Tomcat 9.0.x

**Comment by jamezp** [comment]
@fgrilli Ah okay cool. So you include RESTEasy yourself. We can do a release, but 3.15 is a branch that will not get many updates with 4.7.1.Final being the most recent and 5.0.0.Final coming out very soon.

**Comment by fgrilli** [comment]
Yep, this would be for an earlier version maintenance release of the product. On main we're using 4.6.1 and planning to upgrade :)

**Comment by jamezp** [comment]
@fgrilli It's done and released https://github.com/resteasy/resteasy/releases/tag/3.15.2.Final, I'm updating the web site now.

**Comment by fgrilli** [comment]
@jamezp cheers!

**Pull request merged**
