### PR TITLE
RESTEASY-1418 RESTEasy should be able to provide trace information about request

### PR DESCRIPTION
**Pull request by liweinan**
It's just a preview of the feature. Here are the todo list:

1. We need to put log all the events in RESTEasyServerTracingEvent
2. We need to have ON_DEMAND tracing supported
3. Client side tracing events need to be designed and implemented
4. resteasy-tracing module needs to be removed, because tracing features need to be inside resteasy-jaxrs module.
5. tests...

I'll keep updating this branch.

### CODE REVIEW

**Comment by rsvoboda** [comment]
* tests on WildFly, not just UndertowJaxrsServer
* Documentation, documentation, documentation ;)
* WebConsole / file-system-log-file support to see the tracing data (web console probably via log view facility, I would suggest to have dedicated resteasy-tracing.log file, not to mix server & tracing stuff into server.log)
* Have simple option for admins to disable tracing server wide - to avoid tracing requests processing at all and to save CPU
* [optional] management api support to fetch tracing data
* [to be enterprise level feature] management api support for deployment / server-wide configuration

When I look at https://issues.jboss.org/browse/RESTEASY-1418 it speaks about returning returning tracing logs in response headers. Also request for tracing details is client side driven via special header to request.
When I first looked into this PR I had feeling this is quite server side focused
 * to enable / disable it user needs to reconfigure stuff on the server 
 * to get the tracing data user needs to have access to server logs

Second look revealed that the header support is there.

I miss analysis document on https://github.com/wildfly/wildfly-proposals/pulls with end user scenarios descriptions. Some good older examples can be https://developer.jboss.org/people/brian.stansberry/content Analysis of/Design notes documents, https://developer.jboss.org/wiki/AddingSupportForGitBackendForConfigurationFiles or https://developer.jboss.org/wiki/CLI-BetterCompletionForArguments

Another important aspect is possibility to enable and disable this feature without restart, just for investigation in real traffic. Many users have long time running instances without outages allowed. Just planned restarts in specified periods.

**Comment by liweinan** [comment]
@rsvoboda Thanks for checking and feedback! And I'll check the documents you provided.

Still a long way to complete this feature ^_^

**Comment by liweinan** [comment]
The `ON_DEMAND` mode needs to be supported so users could send tracing request in HTTP header, and get the tracing they want.

```diff
/**
+     * Enable tracing support.
+     * <p>
+     * It allows service developer to get diagnostic information about request processing by RESTEasy.
+     * Those diagnostic/tracing information are returned in response headers ({@code X-RESTEasy-Tracing-nnn}).
+     * The feature should not be switched on on production environment.
+     * <p>
+     * <p>
+     * Allowed values:
+     * <ul>
+     * <li>{@code OFF} - tracing support is disabled.</li>
+     * <li>{@code ON_DEMAND} - tracing support is in 'stand by' mode, it is enabled on demand by existence of request HTTP header</li>
+     * <li>{@code ALL} - tracing support is enabled for every request.</li>
+     * </ul>
+     * Type of the property value is {@code String}. The default value is {@code "OFF"}.
+     * </p>
+     * <p>
+     * The name of the configuration property is <tt>{@value}</tt>.
+     * </p>
+     */
```

**Comment by liweinan** [comment]
In addition, we need to define Client side events. Currently we have `RESTEasyServerTracingEvent` that implements `RESTEasyTracingEvent`, and we need the similar thing for client apis.

**Comment by liweinan** [comment]
The current design *should* support run-time switching on tracing levels(including switch it on/off), in addition with `ON_DEMAND` mode. I'll digging into more details on this.

**Comment by asoldano** [comment]
@rsvoboda , thanks for the feedback. Let me comment a bit on your previous message topics (@liweinan FYI):

>  tests on WildFly, not just UndertowJaxrsServer

+1, it should simply be a matter of having few tests within the testsuite/integration-tests submodule.

>  WebConsole / file-system-log-file support to see the tracing data (web console probably via log view facility, I would suggest to have dedicated resteasy-tracing.log file, not to mix server & tracing stuff into server.log)

IMHO the only thing we should be doing here is make sure the logs from the new tracing facility have a dedicated log category. Then the user can properly tune the logging subsystem and the console can be enriched to show/filter desired logs. In any case, any effort beyond having a dedicated log category should probably go under a separate jira.

>  Have simple option for admins to disable tracing server wide - to avoid tracing requests processing at all and to save CPU

Yep, ideally the goal is for the mechanism to have no impact on performances, when no trace message is written (default behavior). Additionally, it should be possible to enable/trigger logging on demand without having to restart the server.

>  [optional] management api support to fetch tracing data

Probably something for the console project or an external tool that can process logs.

>  [to be enterprise level feature] management api support for deployment / server-wide configuration

I'd say this should go under an additional jira for future enhancements.

**Comment by liweinan** [comment]
`RESTEasyTracingEvent` interface is used to define tracing events, and `RESTEasyServerTracingEvent` is implemented(and events are defined, the next step is to log these events properly).

On the other hands, JBoss Logger has its own logging categories like:

```txt
21:09:08,083 DEBUG [request] Matched default handler path /logger
21:09:08,084 DEBUG [security] Attempting to authenticate HttpServerExchange{ GET /logger request {Connection=[Keep-Alive], User-Agent=[Apache-HttpClient/4.5.4 (Java/9.0.1)], Host=[localhost:8081]} response {}}, authentication required: false
21:09:08,084 DEBUG [security] Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@956019b for HttpServerExchange{ GET /logger request {Connection=[Keep-Alive], User-Agent=[Apache-HttpClient/4.5.4 (Java/9.0.1)], Host=[localhost:8081]} response {}}
21:09:08,084 DEBUG [security] Authentication result was ATTEMPTED for HttpServerExchange{ GET /logger request {Connection=[Keep-Alive], User-Agent=[Apache-HttpClient/4.5.4 (Java/9.0.1)], Host=[localhost:8081]} response {}}
21:09:08,085 DEBUG [general] REQUEST_FILTER Filter by [io.weli.tracing.HttpMethodOverride @150aede3] [ 0.01 ms]
21:09:08,085 DEBUG [general] REQUEST_FILTER Filter by [org.jboss.resteasy.core.AcceptHeaderByFileSuffixFilter @320916e1] [ 0.00 ms]
21:09:08,085 DEBUG [i18n] RESTEASY002315: PathInfo: /logger
21:09:08,085 DEBUG [general] REQUEST_FILTER Filter by [org.jboss.resteasy.plugins.providers.sse.SseEventSinkInterceptor @7c7ad254 #2147483647] [ 0.00 ms]
21:09:08,085 INFO  [general] METHOD_INVOKE Resource [org.jboss.resteasy.plugins.server.resourcefactory.SingletonResource @f4a49] method=[[org.jboss.resteasy.spi.metadata.DefaultResourceMethod @39b74c96]] [ 0.23 ms]
```

Currently we can see the tracing info is under `[general]` category, and we can divide them into finer categories. Let me add this requirement into my TODO list.

**Comment by liweinan** [comment]
According to our discussion, let me create a series of subtasks under [RESTEASY-1418], so we can further  and cleanup this PR

**Comment by asoldano** [comment]
@liweinan sure, go ahead

**Comment by liweinan** [comment]
@asoldano Thanks for confirmation! I'll create subtasks under RESTEASY-1418, and finish this PR asap.

**Comment by liweinan** [comment]
@asoldano According to team discussion, I have created several sub-tasks under RESTEASY-1418 to go on working on the task, and I guess this Pull Request can be treated as an initial commit for review.

**Comment by liweinan** [comment]
The next sub-task I'll work on is RESTEASY-1890

**Comment by liweinan** [comment]
This is the new PR for reviewing: https://github.com/resteasy/Resteasy/pull/1516

**Comment by asoldano** [comment]
I'm closing this as it's superseded by #1533

**Pull request closed without merging**
