### PR TITLE
[RESTEASY-2605] Remove the fallback to URLConnection when SSL is disabled for REST Client

### PR DESCRIPTION
**Pull request by geoand**
The fallback was originally added to get around limitations while using the Apache HTTP Client
when SSL was completely disabled in native binaries.

However we can get around these limitations in a more elegant manner in Quarkus
(see https://github.com/quarkusio/quarkus/pull/9773).

By defaulting to Apache HTTP Client, things like HTTP Patch can be supported
OOTB (see https://github.com/quarkusio/quarkus/issues/9342).

### CODE REVIEW

**Comment by geoand** [comment]
cc @kenfinnigan @asoldano

**Comment by geoand** [comment]
CI failure seems completely unrelated:

```
2020-06-04T08:49:49.6827344Z [INFO] Running org.jboss.resteasy.test.asynch.JaxrsAsyncServletTest
2020-06-04T08:49:56.7587297Z [ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.021 s <<< FAILURE! - in org.jboss.resteasy.test.asynch.JaxrsAsyncServletTest
2020-06-04T08:49:56.9763638Z [ERROR] testResumeObjectThread(org.jboss.resteasy.test.asynch.JaxrsAsyncServletTest)  Time elapsed: 1.018 s  <<< FAILURE!
2020-06-04T08:49:57.1014790Z java.lang.AssertionError: Wrong time of request
2020-06-04T08:49:57.1912871Z 	at org.junit.Assert.fail(Assert.java:88)
2020-06-04T08:49:57.3058187Z 	at org.junit.Assert.assertTrue(Assert.java:41)
2020-06-04T08:49:57.3842822Z 	at org.jboss.resteasy.test.asynch.JaxrsAsyncServletTest.testResumeObjectThread(JaxrsAsyncServletTest.java:197)
```

**Comment by asoldano** [comment]
@geoand the failure is unrelated. Now, I'm wondering if you could add a check for a resteasy system property that could be used for still having the old behaviour. This would allow to merge this in 4.5.4.Final (hopefully very soon) without waiting for next minor (4.6). Clearly we would remove the system property check later (perhaps already in 4.6). WDYT?

**Comment by geoand** [comment]
@asoldano sure, that sounds reasonable to me. What do you want the system property to be called?

**Comment by asoldano** [comment]
@geoand something like org.jboss.resteasy.microprofile.defaultToURLConnectionHttpClient ?

**Comment by geoand** [comment]
@asoldano done

**Comment by asoldano** [comment]
@geoand thanks. I think this is basically fine, just want to ask if you perhaps want to check the property just once (in a static member/block) for performance reasons maybe...

**Comment by geoand** [comment]
Good idea @asoldano!

I'll update the PR to do that tomorrow

**Comment by geoand** [comment]
@asoldano PR updated per your suggestion

**Pull request merged**
