### PR TITLE
[RESTEASY-1227] add testcase, tests stabilization

### PR DESCRIPTION
**Pull request by kanovotn**

### CODE REVIEW

**Comment by asoldano** [comment]
@kanovotn hi, is a corresponding PR against master needed?

**Comment by kanovotn** [comment]
@asoldano https://github.com/resteasy/Resteasy/pull/1194

**Comment by kanovotn** [comment]
@asoldano I have also cherry picked two commits below from jimma from master branch for ResponseStreamPrematurelyClosedTest. If it was merged intentionally only to master I will remove them. 

https://github.com/resteasy/Resteasy/commit/157eeee1afda2e520a590c6699b2ccd926841c66
https://github.com/resteasy/Resteasy/commit/8365522d139867a60fa2606f12ed3873d08f4c5c

**Comment by asoldano** [comment]
@kanovotn well, as long as tests only are backported and they pass,  I have nothing to complain...however, the strange thing is that those tests should be related to / go with https://github.com/resteasy/Resteasy/commit/f2b259976ef041933e91746bde2b28957ba093ef , which is what I didn't backport to 3.0 on purpose. The fact that the tests pass even without that commit is "interesting"...

**Comment by asoldano** [comment]
@kanovotn it might even well be that there's something I'm missing / I don't remember about that jira

**Comment by kanovotn** [comment]
@asoldano I think the testcase ResponseStreamPrematurelyClosedTest is related to this jira RESTEASY-1138 not RESTEASY-1650. RESTEASY-1138 was fixed in 3.0.23 and I my local test run fails as expected with 3.0.22.

**Comment by asoldano** [comment]
@kanovotn ah, right, now I remember. Jim provided additional test.
Thanks, merging then.

**Pull request merged**
