### PR TITLE
[RESTEASY-2260] MP Rest Client 1.3 - default mediatype json

### PR DESCRIPTION
**Pull request by patriot1burke**

### CODE REVIEW

**Comment by ronsigal** [comment]
Hmmm. I looked at the first and last test runs, and they failed with:
```
Running org.jboss.resteasy.test.microprofile.restclient.RestClientProxyTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.416 sec <<< FAILURE! - in org.jboss.resteasy.test.microprofile.restclient.RestClientProxyTest
testGetClient(org.jboss.resteasy.test.microprofile.restclient.RestClientProxyTest)  Time elapsed: 0.207 sec  <<< ERROR!
org.jboss.arquillian.test.spi.ArquillianProxyException: javax.ws.rs.WebApplicationException : Unknown error, status code 406 [Proxied because : Original exception caused: class java.io.NotSerializableException: org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine$1]
```
But RestClientProxyTest passes for me (running current state of branch 3.7).

**Comment by ronsigal** [comment]
In particular,
```
at org.jboss.resteasy.test.microprofile.restclient.RestClientProxyTest.testGetClient(RestClientProxyTest.java:64)
```
I've cloned branch 3.7, merged this PR, and RestClientProxyTest still passes ...

**Comment by ronsigal** [comment]
That line calls
```
    @GET
    @Produces("text/plain")
    @Path("/hello")
    public String hello() {
       return "Hello";
    }
```
Now that "application/json" is the default media type, does the client have to declare it will accept "application/json"? Doesn't explain why it isn't failing for me ...

**Comment by ronsigal** [comment]
Btw, I'm a little behind the curve here. I just re-read the spec. I still have to read/re-read the code.

**Comment by patriot1burke** [comment]
@ronsigal I fixed it.  The test was assuming text/plain when now the default media type is json for MP rest client.  Small one line fix to proxy interface.

**Pull request merged**
