### PR TITLE
RESTEASY-2099

### PR DESCRIPTION
**Pull request by liweinan**
Fix the 3 failed resteasy-link tests after replacing jettison with jackson

### CODE REVIEW

**Comment by liweinan** [comment]
WIP

**Comment by liweinan** [comment]
The JAXB, Jettison and Jackson all are slightly different on supporting JAXB annotations. So I adjusted the test classes so now all the tests are passed under jackson-provider. 

@asoldano @ronsigal Please help to review :D

**Comment by liweinan** [comment]
After this PR get merged, I'll write a resteasy blog entry on jettison -> jackson migration.

**Comment by asoldano** [comment]
@liweinan thanks! Looking forward for the bog entry / doc upgrade

**Pull request merged**
