### PR TITLE
RESTEASY-1206 Create a profile for EAP productization

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
@ronsigal  Could you please help to review this PR? Thanks!

**Comment by ronsigal** [comment]
Sure.

**Comment by ronsigal** [comment]
Hey Wei,

1. I think jaxrs/pom.xml should include resteasy-cdi

2. jaxrs/providers/pom.xml includes fastinfoset, but Wildfly versions 9.0.1.Final and 10.0.0.Alpha6 don't.

-Ron

**Comment by liweinan** [comment]
1. For some modules that are not used by WildFly, they are used by our other products so I enabled them.
2. I've changed the profile name from eap-prod to redhat-prod to reduce the confusion.

Thanks for checking Ron! It seems good to merge this one now, let me take action :-)

**Pull request merged**
