### PR TITLE
Tidy up documentation (chapters 24-55)

### PR DESCRIPTION
**Pull request by alexkieling**
Finished reading the documentation and fixing a few things:

* removed unnecessary empty lines in code snippets
* fixed indentation of some code snippets
* fixed a couple of typos

Pretty good documentation, by the way.

### CODE REVIEW

**Comment by liweinan** [comment]
@alexkieling could you please help to solve the conflicts?

**Comment by alexkieling** [comment]
I'm not sure how to help. I don't have write access to this repository.

**Comment by liweinan** [comment]
It needs to be done in your local branch:
git pull the newest master and merge it with your branch to solve the conflicts.
Then commit and push your updated branch, it will be reflected here.

**Comment by alexkieling** [comment]
Unfortunately I deleted my fork. Feel free to reject this pull request.

**Pull request closed without merging**
