### PR TITLE
[WFLY-13790] added sync block

### PR DESCRIPTION
**Pull request by rsearls**
https://issues.redhat.com/browse/WFLY-13790

### CODE REVIEW

**Review by asoldano — CHANGES_REQUESTED** [review]

**Comment by rsearls** [comment]
@asoldano Please review these changes.

**Comment by bstansberry** [comment]
@rsearls Please edit the PR description and add a link to the JIRA. Thanks!

**Comment by asoldano** [comment]
@rsearls , actually this https://github.com/resteasy/Resteasy/pull/2539 is what I had in mind. Do you believe contextResolver.getContext(..) poses any concurrency risk?

**Comment by rsearls** [comment]
@asoldano I don't think so.

**Comment by asoldano** [comment]
@rsearls , ok, then I'm closing this and merging the other PR (for which a review is welcome anyway)

**Pull request closed without merging**
