### PR TITLE
[RESTEASY-1507] Adding specific catch blocks in ResteasyHandlerMappin…

### PR DESCRIPTION
**Pull request by asoldano**
…g and fixing SpringMvcHttpResponseCodesTest to properly cover all scenarios

### CODE REVIEW

**Comment by asoldano** [comment]
@kanovotn please have a look at this PR, as you prepared the testcase for this issue.

@kanovotn , @ronsigal : note I was not able to have the ResteasyDeployment configured with securityEnabled = true since the beginning to have the RoleBasedSecurityFeature installed and test HTTP 403 scenario using @RolesAllowed annotation.

**Comment by ronsigal** [comment]
* re: RoleBasedSecurityFeature

What has changed so that "resteasy.role.based.security" doesn't work? I assume it used to work with the SpringMVC Dispatcher servlet, though I don't see how, that being one of the servlets that eliminates Resteasy configuration ...

* The new messages in ResteasyHandlerMapping should be i18n'd.

**Comment by asoldano** [comment]
@ronsigal , as for the resteasy.role.based.security, I don't know. We should perhaps check if it was really working in the past. If that's the case, this could be related to one of the changes that we've "recently" applied on the spring integration.

Right, those messages have to be i18n'd.

**Comment by ronsigal** [comment]
re: "We should perhaps check if it was really working in the past."

I'm running SpringMvcHttpResponseCodesTest on Branch_3_0, and what I see is that authentication is being handled in undertow; in particular, io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler in io.undertow:undertow-servlet calls io.undertow.security.impl.SecurityContextImpl in io.undertow:undertow-core.

Hmmm. Now I'm wondering, if, given that undertow handles requests in Wildfly, maybe this is independent of spring and the whole "dueling dispatchers" issue. I.e., maybe "resteasy.role.based.security" is NEVER necessary in Wildfly. If so, then there's an argument for running at least some tests in Jetty or some such alternative servlet container.

**Comment by ronsigal** [comment]
Well, I commented out "resteasy.role.based.security" in web.xml for org.jboss.resteasy.test.security.BasicAuthTest in resteasy-integration-tests, and got four "expected:<403> but was:<200>" failures, so there's something going on. To be continued.

**Comment by ronsigal** [comment]
When BasicAuthTest runs, undertow goes directly to org.jboss.resteasy.plugins.server.servlet.HttpServlet30Dispatcher. 

@asoldano @kanovotn Do you understand this?

**Comment by ronsigal** [comment]
re: "Right, those messages have to be i18n'd."

@asoldano I just pushed a commit to your branch RESTEASY-1507 with the i18n'd messages. I realized after the fact that I should have done it on a new branch. Sorry about that.

**Comment by asoldano** [comment]
@ronsigal wow, np, I just didn't know you could push a commit to someone else branch O_o
As for the other comments above, I'm having a look soon.

**Comment by ronsigal** [comment]
@asoldano Yeah, I didn't know that either. ;-) There must be a flag you can set prevent it.

**Comment by ronsigal** [comment]
@asoldano: Settings -> Branches -> Protected Branches

**Comment by asoldano** [comment]
Going back to the former discussion above, let me remind that authentication != authorization and the javax.annotation.security.* annotations are meant for controlling fine grained authorization that can't be achieved through web.xml. So that why this goes beyond Undertow.

re "When BasicAuthTest runs, undertow goes directly to org.jboss.resteasy.plugins.server.servlet.HttpServlet30Dispatcher."
That's because the web.xml for the deployment in BasicAuthTest does not define any servlet-class, so the WildFly integration code rewrites the web metadata in order to use RESTEasy HttpServlet30Dispatcher .

**Comment by asoldano** [comment]
@ronsigal , can we say that this PR is fine? The problem with not being able to rely on resteasy.role.based.security option is really... a test problem. I propose creating an additional jira for tracking additional investigation of the problem and merging this PR. If you agree, please submit review approval here. Thanks.

**Comment by ronsigal** [comment]
re: "the WildFly integration code rewrites the web metadata in order to use RESTEasy HttpServlet30Dispatcher"

Ah, I didn't know that. Thanks.

**Comment by ronsigal** [comment]
re: "If you agree, please submit review approval here."

Sure, I don't think there's any problem with this PR itself. +1

**Comment by asoldano** [comment]
@ronsigal you might want to go to the "File changed" tab above and then click on the green "Review Changes" button to formally approve the review (as I marked you as reviewer for this PR ;-) )

**Pull request merged**
