### PR TITLE
[RESTEASY-3385] Async request filters using `suspend`/`resume` on `Su…

### PR DESCRIPTION
**Pull request by topak27**
…spendableContainerRequestContext` cause 400 BAD REQUEST

### CODE REVIEW

**Comment by jamezp** [comment]
Yes, these failures are not related. I'm not too sure why these tests have started failing, but it won't block this PR. I just need to check the spec and JavaDoc before I can approve this. I'm trying to understand why it would be activated twice.

**Comment by jamezp** [comment]
My apologies. I thought I asked this earlier, but I did not.

We require all contributions to be made under the terms of the ASL 2.0 License:[ http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0) 
Do you agree to these terms?

**Review by jamezp — APPROVED** [review]

**Comment by topak27** [comment]
> My apologies. I thought I asked this earlier, but I did not.
> 
> We require all contributions to be made under the terms of the ASL 2.0 License:[ http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0) Do you agree to these terms?

yeah, sure!

**Comment by jamezp** [comment]
Waiting for the upstream #3964 to finish, then I'll merge this.

**Pull request merged**
