### PR TITLE
Test intermittent sse failures with TravisCI

### PR DESCRIPTION
**Pull request by asoldano**

### CODE REVIEW

**Comment by asoldano** [comment]
I think RESTEASY-2542 was not fixed completely, regardless of the TravisCI->GithubActions transition, as a matter of fact we have a Sse failure here in the integration-testsuite. Before the fix, though, we also used to have a sse test fail in the vertx server adapter module, which seems to have gone.

**Comment by FroMage** [comment]
This test runs:

```java
try (SseEventSink sink = eventSink)
            {
               logger.info("sending 3 events");
               eventSink.send(builder.data("thing1").build());
               eventSink.send(builder.data("thing2").build());
               eventSink.send(builder.data("thing3").build());
               logger.info("sent 3 events");
            }
```

Which is just wrong, not matter what the spec says, because we're never listening to the returned `CompletionStage` which may throw, or just not be completed by the time we close.

So probably we have an exception and we're ignoring.

**Comment by FroMage** [comment]
@asoldano if you allow me to push to your branch I can add logging, but I've no idea how to enable that logging.

**Comment by asoldano** [comment]
Thanks @FroMage . I think you should now be allowed to push here, sorry for the late reply

**Comment by FroMage** [comment]
@asoldano nope:

```
error: failed to push some refs to 'git@github.com:asoldano/Resteasy.git'
```

**Comment by FroMage** [comment]
errr, I added logging commits, but CI doesn't run on the PR anymore…

**Comment by asoldano** [comment]
@FroMage it's because of the conflict, it has to be rebased

**Comment by asoldano** [comment]
I've rebased and force-pushed.... let's see how it goes

**Comment by asoldano** [comment]
Closing this as the investigation moved to https://github.com/resteasy/Resteasy/pull/2391

**Pull request closed without merging**
