### PR TITLE
[JBEAP-9940] add permissions to testcases

### PR DESCRIPTION
**Pull request by rsearls**

### CODE REVIEW

**Comment by kanovotn** [comment]
None of the tests in this PR pass with 'getClassLoader' permission. Permissions 'accessDeclaredMembers' and 'suppressAccessChecks' are required to make the test pass.

Looking at stacktrace attached to the jira https://issues.jboss.org/browse/JBEAP-9940, why is in this case better to give permission to the deployment, than fixing resteasy or even jackson?

**Comment by rsearls** [comment]
revisions provided

**Comment by rsearls** [comment]
done

**Comment by kanovotn** [comment]
@rsearls Needs rebase.

**Comment by rsearls** [comment]
@kanovotn  Rebase complete

**Comment by asoldano** [comment]
@rsearls github does not allow merging this PR because it conflicts with 3.0 branch, as if the rebase was not completed or not performed properly

**Comment by rsearls** [comment]
I could not resolve the rebase properly.  Removed this PR and submitted a new one.

**Pull request closed without merging**
