### PR TITLE
[RESTEASY-1728] Look for resteasy.allowGzip system property in Regist…

### PR DESCRIPTION
**Pull request by asoldano**
…erBuiltin

This is a proposal for a "fix" applying to both client and server side. Basically every time a new ResteasyProviderFactory instance is created,we would go and check the system property.
This said, we can probably do better... please provide feedback.

### CODE REVIEW

**Comment by ronsigal** [comment]
This is related to the issue that got me thinking about a general purpose facility for checking system properties. Something like
```
         ResteasyConfiguration context = ResteasyProviderFactory.getContextData(ResteasyConfiguration.class);
         if (context != null)
         {
            String s = context.getParameter("resteasy.allowGzip");
            if (s == null)
            {
                 s = AccessController.doPrivileged(new PrivilegedAction<String>() {
                        @Override
                        public String run() {
                            return System.getProperty("resteasy.allowGzip");
                        }
            }
            if (s != null)
            {
               allowGzip = Boolean.parseBoolean(s);
            }
         }
```

**Comment by iweiss** [comment]
@ronsigal Take a look at Elytron's security manager facility, https://github.com/wildfly-security/wildfly-elytron/blob/master/src/main/java/org/wildfly/security/manager/WildFlySecurityManager.java#L1114.

**Comment by asoldano** [comment]
@ronsigal , sure, it's related, and this is probably yet another confirm that we should be implementing your proposal (in that case we'd refactor this fix a bit, should be possible in backward compatible way, right?).
@iweiss , what do you actually want to suggest with the link above?

**Comment by TomasHofman** [comment]
Do you guys think this can be used in 2.3.x branch as it is, so that it's not holding EAP release any longer? If there's going to be some refactoring later on, this branch could perhaps live without it, if it doesn't change a substance of the fix.

**Pull request merged**
