### PR TITLE
[RESTEASY-1596] deleteOnExit on temp file only when the Cleaneable me…

### PR DESCRIPTION
**Pull request by asoldano**
...chanism eventually fails in deleting it

### CODE REVIEW

**Comment by rsearls** [comment]
We have a test in Resteasy for this, EntityBufferingInFileTest.  Currently it is not deploying because it relies on
org.jboss.resteasy.resteasy-legacy which is not present on the server.   
     Caused by: org.jboss.modules.ModuleNotFoundException: org.jboss.resteasy.resteasy-legacy 

working on getting this to run.

**Comment by asoldano** [comment]
@rsearls can you expain better what you mean? I see two EntityBufferingInFileTest files in the sources (one in testsuite/integration-tests, one in testsuite/legacy-integration-tests) and both are part of the build, hence passing. Is there anything to be enabled in those tests, or do they have to be enriched to cover this ?

**Comment by rsearls** [comment]
@ asoldano  There are 2 tests with identical names, 
./testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/client/EntityBufferingInFileTest.java
./testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/EntityBufferingInFileTest.java

The one in legacy-integration-tests is encountered first.  It fails because of the legacy package.
Moving this test a side.  The other one runs.  
I'm still try to confirm the desired code is being executed.

**Comment by asoldano** [comment]
@rsearls ok, given the tests passed here though, I'm wondering if you have local changes on them or what.

**Comment by rsearls** [comment]
@ asoldano
531 ApacheHttpClient4Engine line 531 always succeeds in deleting the
file so the warning message is never written.

I ran the test with this

mvn clean verify \
  -Dserver.home=/home/rsearls/j1/wfly10/wildfly/build/target/wildfly-11.0.0.Beta1-SNAPSHOT \
  -fn -Dtest=EntityBufferingInFileTest \
  -Dmaven.test.redirectTestOutputToFile=false \
  -Djava.io.tmpdir=/tmp/foofoo  \
  -Dmaven.surefire.debug

**Comment by asoldano** [comment]
@rsearls I've manually tested the fix works with the following procedure:
* set a debugger breakpoint on line 531 of ApacheHttpClient4Engine
* delete the file using a console
* step forward with the debugger and let the code fail in deleting the file (as it's not there)
* re-create the file that was previously there, using a console
* disconnect the debugger and let the test finish
* verify the file is not there anymore (as the deleteOnExit causes it to be removed then the JVM shuts down).

As for the legacy test failing, my bet is that's because the server instance you're explicitly telling the testsuite to use is not properly patched to enable the legacy stuff. In this case, to make it easy, simply avoid setting the server.home here and let the testsuite download, patch and run the server he wants.

**Comment by kanovotn** [comment]
@asoldano The issue here is that file.deleteOnExit() keeps the reference even when File.delete() succeeds is it correct?

Maybe another option could be to use try-with-resources with with custom file handler implementing Autoclosable (desribed here - http://stackoverflow.com/a/34050507). With this we could avoif the  usage of deleteOnExit() at all. Just a thought.

**Comment by asoldano** [comment]
@kanovotn, yes the issue being fixed here is that deleteOnExit() is always called, as soon as the file is created. So, despite the file being later deleted (unless something wrong happens on the disk), we still have consumed memory that won't be freed till the JVM goes down (there's basically a static LinkedHashSet<String> instance storing the path of the files marked as to be deleted on exit). This is basically a leak.

This said, we already have a mechanism to figure out when to delete those files (see the CleanableSequenceInputStream), so i believe there's no need for additional AutoCloseable abstraction.
I could have simply just removed the deleteOnExit(), actually that's what I did initially; then I thought it would have been better to keep the deleteOnExit() as a safety net, to be used just in case when we go and delete the file, we fail in deleting it, so we give the system a chance to try performing the cleanup just before shutting down. But that's an exceptional scenario.

**Comment by kanovotn** [comment]
@asoldano  ok, thank you for explanation.

**Pull request merged**
