### PR TITLE
Resteasy-1025 async http client engine

### PR DESCRIPTION
**Pull request by MarkusKull**
Adds a new interface "AsyncHttpClientEngine" deriving from ClientHttpEngine to support truly async communication model. ClientInvocation uses this optional interface if available. 
There is also a behaviour change regarding InvocationCallbacks: the callback is now called in parallel/after the future, similar to jersey. Thus the callback and the future will now see always the same result (and the future will see no exception thrown by callback).

Also included is a implementation for apache httpcomponents httpasyncclient. Care has been taken to not change the existing maven dependencies except of a new optional dependency.

### CODE REVIEW

**Comment by eleduardo** [comment]
This is a very old but very desirable capability on RestEasy specially when consumers need to use their own engine. Netty based clients could really leverage this new interface. Is there any change that this PR or at least this feature would be added to RestEasy?

**Comment by avram** [comment]
As @MarkusKull previously noted, bringing this PR up to date and helping it get a complete review would be a huge step towards that. I know that my teams would be interested in vetting a full-async Netty implementation of this interface and I'm sure others would as well.

**Comment by MarkusKull** [comment]
I will try to bring this PR up-to-date in the next weeks.

**Comment by MarkusKull** [comment]
Updated the PR. Just some minor conflicts.

**Comment by ronsigal** [comment]
Thank you, Marcus. You have not been forgotten.

**Comment by stevenschlansker** [comment]
We're looking into RESTEasy's asynchronous support -- is this PR going to move anytime soon?  Sounds like currently the client does not actually support async calls.

**Comment by liweinan** [comment]
I'm working on migrating this PR: https://github.com/liweinan/Resteasy/tree/resteasy-async-client

**Comment by liweinan** [comment]
https://github.com/resteasy/Resteasy/pull/1228

**Comment by asoldano** [comment]
@MarkusKull , we're eventually moving forward with https://github.com/resteasy/Resteasy/pull/1228 , which is an updated/rebased version of this PR. Unless you already did that in the past, would you mind explicitly writing here that you agree your contributions being made under the ASL 2.0 License http://www.apache.org/licenses/LICENSE-2.0 ? Thanks!

**Comment by MarkusKull** [comment]
@asoldano Good Work! Yes, i agree for my contributions being made under Apache License 2.0 https://www.apache.org/licenses/LICENSE-2.0 .

**Comment by asoldano** [comment]
@MarkusKull , thanks, I've merged the other PR, closing this now.

**Pull request closed without merging**
