### PR TITLE
[RESTEASY-2196] CompletionStageRxInvokerImpl should not block on a th…

### PR DESCRIPTION
**Pull request by anilgursel**
…read.

### CODE REVIEW

**Comment by asoldano** [comment]
Thanks @anilgursel and sorry for the late reply, I've been busy lately. Today I'm reviewing your PR which definitely looks interesting. I might possibly propose you an improvement over your proposal later today/tomorrow, please let me work a bit on this.
In the mean time, we require that all contributions are made under the terms of the ASL2.0 License: http://www.apache.org/licenses/LICENSE-2.0 Do you agree to these terms?
Thanks!

**Comment by asoldano** [comment]
@anilgursel , I've created #1990 , I'm wondering if you can review it. I still need to have it benchmark tested in any case, to see if it really gives benefits.

**Comment by anilgursel** [comment]
@asoldano Yes, I agree on the Apache License 2.0 terms.

**Comment by asoldano** [comment]
Thanks @anilgursel ; btw I'm closing this as we're going on with the discussion on #1990

**Pull request closed without merging**
