### PR TITLE
RESTEASY-1163: use RestEasy's own UriBuilder and clone on resolveTemplate()

### PR DESCRIPTION
**Pull request by eeichinger**
ensure to use RestEasy's own UriBuilder and proper cloning uriBuilder instances on resolveTemplateXXXX()

see https://issues.jboss.org/browse/RESTEASY-1163

### CODE REVIEW

**Comment by ronsigal** [comment]
1. Dependency issues should be resolved outside of Resteasy.
2. The call to UriBuilder.clone() seems to be unnecessary. ResteasyUriBuilder.resolveTemplate() returns a new UriBuilder.

**Comment by eeichinger** [comment]
@ronsigal  you missed the point: it's not about the dependency issue, but in short about the different behaviour of resolveTemplate() in RestEasy and Jersey. Jersey's resolveTemplate() does *not* return a new UriBuilder. If you use RestEasy with Jersey's UriBuilder you end up with very hard to find & debug url problems.

**Comment by ronsigal** [comment]
I'm still missing the point. Why would you use Resteasy with Jersey's UriBuilder?

**Comment by asoldano** [comment]
I'm closing this PR as I basically agree with Ron. The RESTEasy client should not end up being used Jersey stuff, many other weird problem could possibly happen.

**Comment by eeichinger** [comment]
then please at least give out a warning or an error - it happened to us accidentally with maven to have both libs on the classpath, unfortunately jersey's uribuilder got pulled in first. It took as a day to figure out what was wrong.

**Pull request closed without merging**
