### PR TITLE
RESTEASY-2678 - Fix read priority from @Priority with @RegisterProvider.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by asoldano** [comment]
@radcortez , @rsearls , I just realized that the test added in this commit is not executed by default (likely because its name does not end with "Test"). Explicitly running the test result in a failure:

`[INFO] Running org.jboss.resteasy.test.microprofile.restclient.RestClientProviderPriority
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.623 s <<< FAILURE! - in org.jboss.resteasy.test.microprofile.restclient.RestClientProviderPriority
[ERROR] helloUndefined(org.jboss.resteasy.test.microprofile.restclient.RestClientProviderPriority)  Time elapsed: 0.028 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Hello [undefined]> but was:<Hello [Bar]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.jboss.resteasy.test.microprofile.restclient.RestClientProviderPriority.helloUndefined(RestClientProviderPriority.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
`

@radcortez , WDYT? I'd need to revert this unless the situation is clarified / fixed soon ;-)

**Comment by radcortez** [comment]
Hum, sorry about that. I was running the test directly on my IDE, so I had no issue with the `Test` suffix. I'll send a new PR to fix it. If you prefer to revert this one, it is also fine.

**Comment by asoldano** [comment]
thanks @radcortez , if you're sending a fix fairly soon, I can wait without reverting.

**Comment by radcortez** [comment]
Here: https://github.com/resteasy/Resteasy/pull/2519

**Pull request merged**
