### PR TITLE
[RESTEASY-2169] AsyncResponse resume omits GenericEntity type

### PR DESCRIPTION
**Pull request by TuomasKiviaho**
When GenericEntity is given then methods generic return type isn't used

### CODE REVIEW

**Comment by asoldano** [comment]
Hi @TuomasKiviaho , we require that all contributions be made under the terms of the ASL 2.0 License: http://www.apache.org/licenses/LICENSE-2.0
Do you agree to these terms?

**Comment by TuomasKiviaho** [comment]
I agree

**Comment by ronsigal** [comment]
Hi @TuomasKiviaho,

This change looks reasonable to me. Two requests, if you can:
1. Can you supply a simple test?
2. Can you create a pull request for master branch?

Thanks for your contribution!
-Ron

**Comment by ronsigal** [comment]
I've created pull request https://github.com/resteasy/Resteasy/pull/1981 to replace this one. It's the same, plus a test. Thanks, @TuomasKiviaho, for your work.

**Pull request closed without merging**
