### PR TITLE
Add listener constructor

### PR DESCRIPTION
**Pull request by Sineaggi**
This allows for code such as
```
Server server = new Server(8080);
ServletContextHandler contextHandler = new  ServletContextHandler(ServletContextHandler.SESSIONS);
AnnotationConfigWebApplicationContext rootContext = new AnnotationConfigWebApplicationContext();
rootContext.register(AppConfig.class);
contextHandler.addEventListener(new ResteasyBootstrap());
contextHandler.addEventListener(new SpringContextLoaderListener(rootContext));
contextHandler.addServlet(HttpServletDispatcher.class, "/*");
server.setHandler(contextHandler);
server.start();
server.join();
```

to be used inside of a servlet 3.0 container such as the Jetty server, without requiring `web.xml` and `applicationContext.xml` files.

### CODE REVIEW

**Comment by Sineaggi** [comment]
Whoops, I just checked the pom file. The `resteasy-spring` project uses Spring 3.0.6.RELEASE as it's spring version. Is there a plan to bump spring version numbers?

**Comment by asoldano** [comment]
@Sineaggi we'll eventually upgrade to a more recent spring version in the future, not now though. What is the minimum requirement for your change here, Spring 4.3.0?

**Comment by Sineaggi** [comment]
@asoldano I've just tested, Spring 4.0.0 is the minimum requirement. I can try to investigate if we could add a method that sets the `WebApplicationContext`, while not requiring a constructor-based invocation. It would appear that `AnnotationConfigWebApplicationContext` is also available in Spring 3.0.0 so it may be possible. If not, `applicationContext.xml` is a file alternative for the time being.

**Comment by Sineaggi** [comment]
Not sure what the failing test is about.
```
Failed tests: 
  AsynchBasicTest.testAsynchTen:273 expected:<200> but was:<202>
Tests run: 1243, Failures: 1, Errors: 0, Skipped: 1
```

**Comment by Sineaggi** [comment]
Fixed, seems like it was a fluke.

**Comment by asoldano** [comment]
OK, thanks. Currently reasoning on the implications of spring upgrade, to decide when to merge this PR.

**Comment by asoldano** [comment]
OK, I've squashed your commits in a single one and merged upstream after having moved to Spring 3.1.0.RELEASE. Thanks!

**Comment by Sineaggi** [comment]
Thank you!

**Comment by UltimaPhoenix** [comment]
I hope that this time the pull request will not be reverted anymore, ref. my previous accepted then reverted pull request https://github.com/resteasy/Resteasy/pull/623

**Pull request closed without merging**
