### PR TITLE
[RESTEASY-1741] Dependencies update

### PR DESCRIPTION
**Pull request by rsvoboda**
https://issues.jboss.org/browse/RESTEASY-1741

Dependencies update to catch up with upstream and WF dependencies.
Some dependencies updates are causing problems, will be solved case by case.

### CODE REVIEW

**Comment by rsvoboda** [comment]
Java 9 fails :( The rest is OK.

**Comment by rsvoboda** [comment]
I get PASS on my local machine when ddb8f528fcdc7fdd7eba2303b2eee90f128353e5 commit is combined with
```diff
-            <modular.jdk.args>--add-modules=java.se</modular.jdk.args>
+            <modular.jdk.args>--add-modules=java.se,java.xml.bind</modular.jdk.args>
```

@asoldano is it ok for you to enhance `add-modules` by `java.xml.bind` ?

**Comment by rsvoboda** [comment]
jaxb shift from 2.2.7 to 2.2.11.jbossorg-1
and there is split in jaxb packages - core + impl etc.

but do not know details what could trigger the need for java.xml.bind in add-modules tbh

**Comment by asoldano** [comment]
@rsvoboda FYI, this https://github.com/asoldano/jbossws-cxf/commit/50007e8e7baff47bd84ae39820d8f0730716d780 is what has just allowed me to stay with java.se module dependency only in jbossws and consume jaxb-runtime from maven dependencies instead.

**Comment by rsvoboda** [comment]
Hi @asoldano, I tried to add javax.activation:activation to the first failing module (providers/jackson) but see the same exceptions.

```
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

```
Feels like I need jaxb-api dependency ... either via add-module or javax.xml.bind:jaxb-api:2.3.0

**Comment by asoldano** [comment]
This is superseded by https://github.com/resteasy/Resteasy/pull/1332

**Pull request closed without merging**
