### PR TITLE
RESTEASY-2664: Add a way to customize header filing for ClientHeaderParam

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
relates to https://github.com/quarkusio/quarkus/issues/10249

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
The failing job's error seems to be:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project resteasy-integration-tests-spring-unit: Unable to generate classpath: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information for org.apache.maven.surefire:surefire-junit47:jar:2.22.0: Failed to retrieve POM for org.apache.maven.surefire:surefire-junit47:jar:2.22.0: Failure to transfer org.apache.maven.surefire:surefire-junit47:pom:2.22.0 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.maven.surefire:surefire-junit47:pom:2.22.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit47/2.22.0/surefire-junit47-2.22.0.pom
```

I will do some small change to retrigger the checks

**Comment by michalszynkiewicz** [comment]
@rsearls @ronsigal any chance you could take a look at it soon?
Are there any releases planned in the near future that this could go in?

**Comment by asoldano** [comment]
@michalszynkiewicz , we'll be reviewing this soon, sorry for the delay. Would you mind creating a jira at https://issues.redhat.com/projects/RESTEASY . As for the release this could go in, I'd say 4.6.0.Final, which I'd like yo see before the end of the summer.

**Comment by michalszynkiewicz** [comment]
@asoldano I created an issue, please let me know if the description is too cryptic

**Comment by asoldano** [comment]
Thanks @michalszynkiewicz . As a preliminary review, I'm wondering if you could add some testing coverage. Moreover, is the addition worth any mention in the resteasy userguide?

**Comment by michalszynkiewicz** [comment]
@asoldano @rsearls I'll add some tests. Do you think I could pull out another module from the mp rest client module, sth like mp rest client base, that would not contain the default implementation? The default impl causes warnings in newer java versions.

**Comment by michalszynkiewicz** [comment]
I added a test. I also pulled out most of MP Rest Client to a separate module, so that vendors don't have to have the default header filling classes on the classpath if they want to provide a different impl.

I didn't update the docs though. From what I see, they are rather user focused. This modification is meant to be used by vendors

**Comment by michalszynkiewicz** [comment]
The one job that failed, failed with 
```
Could not transfer artifact org.apache.maven.surefire:surefire-junit47:pom:2.22.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit47/2.22.0/surefire-junit47-2.22.0.pom
```

**Comment by asoldano** [comment]
@michalszynkiewicz , I've resolved the conflicts and merged this on master, see https://github.com/resteasy/Resteasy/commit/c4a1715c8b389d5ec202a35f47370053c4dc27c1 
Thanks

**Comment by yuhaibohotmail** [comment]
Why is this PR not merged?

**Comment by michalszynkiewicz** [comment]
@yuhaibohotmail I checked 4.5.8 too and it's not there.

@asoldano should I create a pull request targetting 4.5 for it?

**Pull request closed without merging**
