### PR TITLE
[Testsuite] Management address for spring in deployment tests

### PR DESCRIPTION
**Pull request by kanovotn**

### CODE REVIEW

**Comment by asoldano** [comment]
@kanovotn , this has been forgotten for a while... is it still needed / shall I merge, or we don't care about this anymore?

**Comment by kanovotn** [comment]
@asoldano Yes, this is needed, could we have this cherry picked into 3.5 and master branches? Or should I create PR for them?

**Comment by asoldano** [comment]
@kanovotn OK, thanks, please create the PRs :-)

**Comment by kanovotn** [comment]
The PRs: https://github.com/resteasy/Resteasy/pull/1628 https://github.com/resteasy/Resteasy/pull/1627

**Comment by asoldano** [comment]
@kanovotn thanks, I've merged those 2 PRs. Closing this. Thanks!

**Pull request closed without merging**
