### PR TITLE
[RESTEASY-2510] Split RESTUtils to links provider and injector

### PR DESCRIPTION
**Pull request by gytis**
https://issues.redhat.com/browse/RESTEASY-2510

I'm building a Quarkus extension in which I would like to make a use of `resteasy-links` module. In this PR I've introduced a few changes that would make it easier to use this module in the said extension:

1. Added `entityClassName` field to the `@LinkResource` annotation. This will allow to generate JAX-RS resources with `@LinkResource` annotation during the build time in Quarkus.
2. Split `RESTUtils` class into two classes: `ObjectLinksProvider` and `LinksInjector`. This will allow to get links relevant to an object without injecting them into its field.
3. Add `ClassLinksProvider`. This will allow to get links relevant to a class (`list` and `add` operations that work with a given class)

Most of what I've done is reorganise the code. The procedure of finding links is unchanged.

### CODE REVIEW

**Comment by gytis** [comment]
Should I create a JIRA issue as per contribution guidelines?

**Comment by gytis** [comment]
cc @FroMage

**Comment by liweinan** [comment]
@gytis yes please create relative jira issue

**Comment by gytis** [comment]
I've renamed commit message to include a JIRA issue.

**Comment by liweinan** [comment]
I rerun the failed tests and it passed. The PR looks awesome to me. Add @ronsigal and @asoldano as reviewers.

**Pull request merged**
