### PR TITLE
RESTEASY-2734 The current WADL GRAMMAR generation logic incorrectly c…

### PR DESCRIPTION
**Pull request by liweinan**
…lean the schema types

### CODE REVIEW

**Comment by liweinan** [comment]
This PR fixed the previously incorrect grammar regeneration logic which exposes during Wildfly deployment.

**Comment by liweinan** [comment]
sample app to prove the fix:

- https://github.com/liweinan/resteasy-wildfly

deployment on wildfly and the query result:

image

**Comment by liweinan** [comment]
I'll do some final check and then remove InProgress tags.

**Comment by liweinan** [comment]
The previous design of  `ResteasyWadlDefaultResource` was incorrect, and `ResteasyWadlDefaultResource` needs to be `abstract` so users can customize it. For example, set the path or inject grammar generation settings:

image

After this PR is done, I'll update document accordingly.

**Comment by liweinan** [comment]
not sure why test failed on CI(looks like jboss-modules is not found correctly, not relevant to this PR), test passed locally:

image

**Review by asoldano — APPROVED** [review]

**Comment by ronsigal** [comment]
Hey @liweinan,

First, I apologize for not knowing anything about the WADL support that you've worked on so much. 

Now I'm trying to understand. 

1. When I add a simple resource
```
@Path("other")
public class MyOtherResource extends ResteasyWadlDefaultResource {
	
	@GET
	@Path("test")
	public String test() {
		return "ok";
	}
}
```
I get output
```
<application>
  <resources base="http://localhost:8080/WADLTest-0.0.1-SNAPSHOT">
    <resource path="other">
      <resource path="/wadl-extended/{path}">
        <param name="path" style="template" type="xs:string"/>
        <method id="grammars" name="GET">
          <response>
            <representation mediaType="application/xml"/>
          </response>
        </method>
      </resource>
      <resource path="/application.xml">
        <method id="output" name="GET">
          <response>
            <representation mediaType="application/xml"/>
          </response>
        </method>
      </resource>
      <resource path="test">
        <method id="test" name="GET">
          <response/>
        </method>
      </resource>
    </resource>
    <resource path="/">
      ...
    </resource>
  </resources>
</application>
```
Should there be a "/wadl-extended/{path}" "/application.xml" under resource "other"?

2. My MyWadlResource looks like
```
@Path("/")
public class MyWadlResource extends ResteasyWadlDefaultResource {
	
    public MyWadlResource() {
        ResteasyWadlWriter.ResteasyWadlGrammar wadlGrammar = new ResteasyWadlWriter.ResteasyWadlGrammar();
        wadlGrammar.enableSchemaGeneration();
        getWadlWriter().setWadlGrammar(wadlGrammar);

    }
}
```
but http://localhost:8080/WADLTest-0.0.1-SNAPSHOT/wadl-extended/xsd0.xsd returns
```
XML Parsing Error: no root element found
Location: http://localhost:8080/WADLTest-0.0.1-SNAPSHOT/wadl-extended/xsd0.xsd
Line Number 1, Column 1:
```
What am I doing wrong?

Thanks,
Ron

**Pull request merged**
