### PR TITLE
[RESTEASY-2820] Clients running in a resource method throw safer WebA…

### PR DESCRIPTION
**Pull request by nikosmoum**
…pplicationException (#2632)

[RESTEASY-2820] Removed smallrye reference from resteasy-client-api POM.

### CODE REVIEW

**Comment by nikosmoum** [comment]
Notes:
- This is an almost entirely clean cherry-pick of the RESTEASY-2781 change, for the purpose of backporting to 4.4
- I agree with the Apache License 2.0 terms

**Comment by nikosmoum** [comment]
@ronsigal Please let me know if there's anything else is needed for this PR!

**Comment by ronsigal** [comment]
Hi @nikosmoum,

I've got a couple of other releases due soon, but I hope to get to this soon, probably late next week. Haven't forgotten, though. :)

-Ron

**Comment by nikosmoum** [comment]
Hi @ronsigal, any update on when this might be available?
Thanks,
Nikos

**Comment by ronsigal** [comment]
Hi @nikosmoum,

Sorry, the release of 3.15.0.Final was more involved than I expected. Barring surprises, I'll try to do this this week.

-Ron

**Comment by nikosmoum** [comment]
@ronsigal Thanks!

**Comment by ronsigal** [comment]
Hey @nikosmoum, you're very welcome. ;)

**Comment by ronsigal** [comment]
Hey @nikosmoum, you're very welcome. :)

**Comment by gastaldi** [comment]
> Sorry, the release of 3.15.0.Final was more involved than I expected. Barring surprises, I'll try to do this this week.

Can this fix be cherry-picked to the 3.15.x branch?

**Pull request merged**
