### PR TITLE
[RESTEASY-2254]

### PR DESCRIPTION
**Pull request by asoldano**

### CODE REVIEW

**Comment by patriot1burke** [comment]
Should you backmerge your fix to the rx provider to 3.8?

**Comment by ronsigal** [comment]
This is just @patriot1burke's PR for 3.8, right?

**Comment by asoldano** [comment]
> Should you backmerge your fix to the rx provider to 3.8?

I don't think so, that the CompletionStage rx invoker is different on 3.8.

**Comment by asoldano** [comment]
> This is just @patriot1burke's PR for 3.8, right?

Yep, basically, it keeps master and 3.8 aligned

**Comment by asoldano** [comment]
> Not much to say here :) TCK tests (1.2.1) passed, no regression found in the CI jobs.
> 
> @patriot1burke thanks for the update
> 
> There is https://github.com/eclipse/microprofile-rest-client/releases/tag/1.3.1 release.
> What are plans around it ?
> First in https://github.com/smallrye/smallrye-rest-client/ and later backport to RESTEasy ?

AFAIK the work for upgrading to 1.3 is in progress. See https://github.com/resteasy/Resteasy/pull/2047 for example.

**Pull request merged**
