### PR TITLE
RESTEASY-1784 - Exception during chunked transfer is suppressed

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
It's hard to test this case in RESTEasy itself, because it relies on underlying web servers(tomcat, jetty, etc). So I put the test case here:

* https://github.com/liweinan/RESTEasy1784Reproducer

image

Here is the running status under Jetty:

image

image

image

image

**Comment by liweinan** [comment]
tested against tomcat9:

image

image

image

**Comment by asoldano** [comment]
@liweinan can you please rebase this to solve the conflicts? Thanks

**Comment by liweinan** [comment]
@asoldano done!

**Comment by asoldano** [comment]
@liweinan , I apologize, this needs rebase again.

**Comment by liweinan** [comment]
@asoldano No problem! I'll finish rebasing this before my PTO this week.

**Comment by liweinan** [comment]
@asoldano @ronsigal Because rebasing is too expensive(many conflicts) so I create a new PR here:

https://github.com/resteasy/Resteasy/pull/2613

**Pull request closed without merging**
