### PR TITLE
RESTEASY-1323 / RESTEASY-1325

### PR DESCRIPTION
**Pull request by ronsigal**
Extended timeouts to fix travis problems.

### CODE REVIEW

**Comment by ronsigal** [comment]
I'm going to go ahead and commit this, since it (seems to) fix a couple of tests that have been breaking travis runs.

**Comment by asoldano** [comment]
+1

**Comment by asoldano** [comment]
However  a build of master has failed after this commit, so looks like the changes are not enough (https://travis-ci.org/resteasy/Resteasy/builds/128555441)

**Comment by ronsigal** [comment]
Damn.

**Pull request merged**
