### PR TITLE
Look properly at superclasses.

### PR DESCRIPTION
**Pull request by mihxil**
Original pull request was https://github.com/resteasy/Resteasy/pull/615

### CODE REVIEW

**Comment by ronsigal** [comment]
Can you do two things for me?

1. Create a JIRA issue at https://issues.jboss.org/projects/RESTEASY explaining the issue.
2. Remove the formatting changes.

Thanks,
Ron

**Comment by mihxil** [comment]
The issue as created already: https://issues.jboss.org/browse/RESTEASY-1212

**Comment by ronsigal** [comment]
Ok, thanks.

**Comment by mihxil** [comment]
Dammit, obviously I'm making a mess of this pull request.

**Comment by mihxil** [comment]
I give up, a clean pull request is here

https://github.com/resteasy/Resteasy/pull/736

**Comment by asoldano** [comment]
I'm closing this PR as it was superseded by #736 (which was also merged).

**Pull request closed without merging**
