### PR TITLE
Add the ability to use the Java HttpClient as the default HttpClientE…

### PR DESCRIPTION
**Pull request by jamezp**
…ngine.

### CODE REVIEW

**Comment by jamezp** [comment]
> This is great!

Thank you. I'm not sure why these tests are failing as they pass, at least on Linux, for me locally. I'm on a new laptop so I need to get a new Windows VM setup to test there.

**Comment by liweinan** [comment]
It seems like some random async problems.

**Comment by jamezp** [comment]
> It seems like some random async problems.

Yes, in some cases it looks like the connection gets closed so it could be a real issue. I just have been able to reproduce it.

**Comment by jamezp** [comment]
Please also see the discussion https://github.com/resteasy/resteasy/discussions/3743

**Pull request closed without merging**
