### PR TITLE
[RESTEASY-1566]

### PR DESCRIPTION
**Pull request by ronsigal**
I've merged the code from https://github.com/resteasy/Resteasy/pull/1093
into master branch, along with documentation in StringConverter.xml in
the User Guide.

### CODE REVIEW

**Comment by ronsigal** [comment]
This pull request replaces https://github.com/resteasy/Resteasy/pull/1093.

**Comment by ronsigal** [comment]
This replaces https://github.com/resteasy/Resteasy/pull/1093. I would like Nicolas NESMON to take a look before we merge it.

-Ron

**Comment by asoldano** [comment]
@NicoNes please see above :-)

**Comment by NicoNes** [comment]
Hi @ronsigal  and @asoldano,

This merged PR is good to me.

Thanks

**Pull request merged**
