### PR TITLE
* feat(resteasy-guice): add back the Google Guice integration

### PR DESCRIPTION
**Pull request by desaerun**
Guice 7.0.0 is fully on the jakarta namespace now.
 Reverts 8e64b0650e0066ac1b73299affac3facd182a988

### CODE REVIEW

**Comment by jamezp** [comment]
For now I'll leave this open, but I don't think we want Guice back in RESTEasy. We could make a separate project or add it to the [resteasy-extensions](https://github.com/resteasy/resteasy-extensions). I don't think it belongs in RESTEasy though. 

Another thing to note is in Jakarta REST 4.0 CDI is going to be replacing the `@Context` injection. This will likely cause a refactor of how we use injection. Part of the plan is to hopefully make it more plugable for other DI frameworks.

**Comment by RWSalexjarvis** [comment]
Hey, no problem! I was bumping the dependencies on an old project and ended up using a hacked-together version of this to get resteasy and guice working together again, so I figured with Guice being on jakarta it might be useful to add `resteasy-guice` back in (since the rationale for removing it in the first place was that they weren't migrating to the jakarta namespace fast enough).

Thanks for your review in any case.

**Comment by desaerun** [comment]
Hey, no problem! I was bumping the dependencies on an old project and ended up using a hacked-together version of this to get resteasy and guice working together again, so I figured with Guice being on jakarta it might be useful to add resteasy-guice back in (since the rationale for removing it in the first place was that they weren't migrating to the jakarta namespace fast enough).

Thanks for your review in any case.

**Comment by jamezp** [comment]
My apologies for the delay on replying to this. This is something we could consider adding support again for. However, it should be it's own separate project which we can create. If we do this, there will be a need for community support. This is something I'm not too familiar with and do not use in any other projects.

**Comment by jamezp** [comment]
This was moved to https://github.com/resteasy/resteasy-guice

**Pull request closed without merging**
