### PR TITLE
Restore integration-test execution

### PR DESCRIPTION
**Pull request by asoldano**

### CODE REVIEW

**Comment by asoldano** [comment]
@jimma FYI, just figured out one of your PR (the one you added a new surefire execution for the json b test) accidentally disabled the whole integration-testsuite.

**Comment by asoldano** [comment]
Merged immediately to prevent regressions. We can improve the solution in other commits, if needed.

**Comment by jimma** [comment]
@asoldano Can you explain why that change disabled the whole integration test suite ?

**Comment by asoldano** [comment]
@jimma I'm not 100% sure, it has to do with mixed configuration in plugin and plugin execution, plus one of the execution being the default one. I just noticed that the build was taking way less time than before and then noticed that no test was run in that module. So I applied the same "setup" that we've been using successfully for years in JBWS (disable default execution and explicitly enable 2 new ones, avoiding mixing includes and excludes in the same execution config) and it solved the problem.

**Pull request merged**
