### PR TITLE
[RESTEASY-2244] @Produces not picked up well

### PR DESCRIPTION
**Pull request by spyrkob**
JIRA: https://issues.jboss.org/browse/RESTEASY-2244

### CODE REVIEW

**Comment by ronsigal** [comment]
Thanks, @spyrkob. Would you be interested in writing a test in which the return media type comes from the resource class?

**Comment by spyrkob** [comment]
@ronsigal sure, can do that, but without some hackery it won't be possible to reproduce the issue as the correct Producer would be returned by the method.getProduces() already.

**Comment by ronsigal** [comment]
@spyrkob, yeah, you're right. Good point. I suspect that the best practice would be to have a test in place just to prevent any future regressions. With a note explaining that there is currently no way for the test to fail. If you don't mind. ;-)

**Comment by spyrkob** [comment]
@ronsigal added the test, let me know if it looks OK

**Comment by spyrkob** [comment]
@asoldano sorry my IDE must have messed up something... should be fixed now

**Pull request merged**
