### PR TITLE
Back port couple of fixes for PatchMethodFitler

### PR DESCRIPTION
**Pull request by jimma**
This PR backport  these changes:
[RESTEASY-2165]:Add json merge patch support
[RESTEASY-2496]:Add configuration parameter to disable PatchMethodFitler
[RESTEASY-2280]:PatchMethodFilter GET requires Consumes APPLICATION_JSON_PATCH_JSON

### CODE REVIEW

**Comment by jimma** [comment]
@asoldano  Can we simply add the target version 3.12 to RESTEASY-2165 and RESTEASY-2496 ?

**Comment by ronsigal** [comment]
@jimma, @asoldano,

This looks like a Feature, and EAP7-1494 is still in Backlog. Maybe I should change the tag to 3.13 ...

-Ron

**Comment by asoldano** [comment]
@ronsigal unfortunately, yes

**Comment by ronsigal** [comment]
Ok, I've pushed

1. RESTEASY-2167 "Add docs and example for json patch support" and
2. RESTEASY-2567 "Add Json Merge Patch support"

to 3.13.0.Final.

**Comment by asoldano** [comment]
I'm closing this as there's no plan for releasing a new 3.12.x version, next one on the 3.x series will be 3.13.0.Final.

**Pull request closed without merging**
