### PR TITLE
[RESTEASY-2573] ResteasyContext never popped for SSE async streams

### PR DESCRIPTION
**Pull request by FroMage**
Fix for https://issues.redhat.com/projects/RESTEASY/issues/RESTEASY-2573

### CODE REVIEW

**Comment by asoldano** [comment]
@FroMage, just yesterday I restore the tests that were excluded because of RESTEASY-2542 and we also moved to GitHub actions for the CI testing. Unfortunately, it looks like we still have intermittent SSE test failures. So, first of all I'd as you if you can rebase this PR against master as I've excluded again one test that seem to fail very frequently. Then we should investigate the failures (I'm asking Jim too as soon as he's back from holiday). Moreover, if you want to test this PR with the old TravisCI solution, we can do that as well (just let me know). Thanks.

**Comment by FroMage** [comment]
@asoldano I just rebased on master. Do I need to do anything to get CI to run on GitHub Actions instead of Travis? I see travis kicked in, for some reason.

**Comment by FroMage** [comment]
Failure:

```
2020-05-06T12:36:03.9790684Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project resteasy-unit-tests: Unable to generate classpath: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information for org.apache.maven.surefire:surefire-junit47:jar:2.22.0: Failed to retrieve POM for org.apache.maven.surefire:surefire-junit47:jar:2.22.0: Could not transfer artifact org.apache.maven.surefire:surefire-junit47:pom:2.22.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit47/2.22.0/surefire-junit47-2.22.0.pom
```

**Comment by asoldano** [comment]
@FroMage thanks for the rebase. Now, here as well as on master, GithubActions runs are enabled. You see also a travis run with a single job for the Elytron integration testing only.
Earlier today I've created a branch for reproducing the SSE failures with the old Travis only (#2387 ) and got a failure on the first run, so I can say that the problem is there regardless of the CI mechanism being used.

**Comment by WillSmithTE** [comment]
I know it's not been long, but is there any rough ETA on this one?

**Comment by asoldano** [comment]
@WillSmithTE , I can't say for sure, but I believe this will be included in next release of 4.x series, which should come fairly soon.

**Comment by asoldano** [comment]
@FroMage , can you please rebase again?

**Comment by FroMage** [comment]
Done.

**Pull request merged**
