### PR TITLE
[RESTEASY-1366]: fixed Jackson2Provider client deserialization…

### PR DESCRIPTION
**Pull request by askannon**
…regression that was introduced in version 3.0.14 that breaks the Jackson @JsonView feature

### CODE REVIEW

**Comment by asoldano** [comment]
Cool, thanks for the patch. Any chance you can also add a testcase? Thanks

**Comment by asoldano** [comment]
@askannon  (otherwise I'll prepare one later this week)

**Comment by askannon** [comment]
I added tests as well as fixed the same bug for the writer in addition to the reader.

**Comment by askannon** [comment]
Any chance to get this merged into WildFly 10.1? Without this patch we can't upgrade to WF10 at all because @JsonView is broken.

**Comment by asoldano** [comment]
OK, I'm closing this PR (would have needed you to rebase against current master which changes quite a bit since you opened this), but I've merged your changes on master and added the same testcase you provided but in a different project module.
As for the changes being included in WildFly 10.1, it really depends on WildFly release date; I'm most likely merging this fix to RESTEasy 3.0.x branch, so either 3.0.19.Final will be included in WildFly 10.1.0.Final or you'll have to install it manually afterwards on top WildFly 10.1.0.Final (or current WildFly 10.0.0.Final).

**Comment by asoldano** [comment]
Ah, and thanks a lot for the contribution ;)

**Pull request closed without merging**
