### PR TITLE
2266

### PR DESCRIPTION
**Pull request by ronsigal**

### CODE REVIEW

**Comment by ronsigal** [comment]
Waiting for @anilgursel to check it out.

**Comment by ronsigal** [comment]
Ooops. My commit for "[RESTEASY-2267] Update user guide chapter on MicroProfile config." snuck in.

**Comment by anilgursel** [comment]
@ronsigal The change looks good to me.  Thanks!

**Comment by ronsigal** [comment]
Excellent, @anilgursel. I'll straighten out the conflicts and commit. Thank you.

**Comment by ronsigal** [comment]
Replaced by https://github.com/resteasy/Resteasy/pull/2077.

**Pull request closed without merging**
