### PR TITLE
[RESTEASY-2874] Web Target Proxy not overriding content type header

### PR DESCRIPTION
**Pull request by petrberan**
https://issues.redhat.com/browse/RESTEASY-2874

### CODE REVIEW

**Comment by liweinan** [comment]
@ronsigal @jamezp this looks good. Can it be merged?

**Comment by jamezp** [comment]
Thank you for the contribution. We are cleaning up older PR's that seem to be stale. If you feel this is still an issue please feel free to re-open.

**Comment by jamezp** [comment]
@crankydillo Let me think about this. That example seems explicit to me that the user would want to set the `Content-Type` header. However, the entity value should win IMO. It does seem like we should file an issue for this.

**Comment by crankydillo** [comment]
I went ahead and wrote it up [here](https://issues.redhat.com/browse/RESTEASY-3303), primarily so we'll have something to track.  I probably should have done that initially, but I always have to dig out my JIRA account info:P

**Pull request merged**
