### PR TITLE
RESTEASY-2113 Fix testELWorksWithoutPackageJSON

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
This is based on https://github.com/resteasy/Resteasy/pull/1801

**Comment by liweinan** [comment]
And this is a subtask of https://issues.jboss.org/browse/RESTEASY-2099

**Comment by asoldano** [comment]
@liweinan , this actually supersedes #1801, right?

**Comment by liweinan** [comment]
@asoldano Right. I split them just because I'm working on the three failed tests one by one and can't estimate the workload in advance. And this test seems easy to fix :)

**Comment by asoldano** [comment]
@liweinan please rebase against master

**Comment by liweinan** [comment]
Because we have merged `@AddLink` and `@AddJsonLink`, let me close this PR and recreate one.

**Pull request closed without merging**
