### PR TITLE
Add support for Microprofile RestClient API

### PR DESCRIPTION
**Pull request by heiko-braun**
This provides an implementation of the Microprofile RestClient specification 1.0. Your review and thoughts are appreciated.

- Specification: https://github.com/eclipse/microprofile-rest-client/releases/tag/microprofile-rest-client-1.0
- CDI Extensions and TCK Runner: https://github.com/heiko-braun/mp-rest-client-impl

### CODE REVIEW

**Comment by heiko-braun** [comment]
I see the testsuite failures and am working on it.

**Comment by asoldano** [comment]
Thanks

**Comment by heiko-braun** [comment]
Looks good :)

**Comment by heiko-braun** [comment]
Btw, I would prefer to use this PR for review purposes and not merge it yet. There are still things missing, i.e. license headers and such.

**Comment by asoldano** [comment]
@heiko-braun , ok, I've added the "Do not Merge" label, feel free to remove it when you want (or I can do that).
This said, so far I think the changes are good. It would be great if you could provide few tests, to reduce risk of potential regressions due to future changes.

**Comment by heiko-braun** [comment]
I think to get test coverage the best would be to run the microprofile TCK. I need to carry that over from here:  https://github.com/heiko-braun/mp-rest-client-impl

**Comment by heiko-braun** [comment]
@asoldano @liweinan I've added the TCK testsuite and did carry over the remaining pieces (CDI extension) to align with the specification.  From my point of view this would be good to merge, unless you have change requests.

**Pull request merged**
