### PR TITLE
[RESTEASY-2503] @Valid annotation on parameter doesn't get picked up …

### PR DESCRIPTION
**Pull request by gaol**
…by subclass

Issue: https://issues.redhat.com/browse/RESTEASY-2503

This is the back port of https://github.com/resteasy/Resteasy/pull/2308 to `3.6.1.SPx` branch for `EAP 7.2.x`

EAP 7.2 issue: https://issues.redhat.com/browse/JBEAP-18740

### CODE REVIEW

**Comment by gaol** [comment]
@ronsigal @asoldano would you please review? Thanks

**Comment by gaol** [comment]
@ronsigal  I updated the PR to define a `Utils.isStatelessOrSingleton()` in `resteasy-cdi` module to check if the method's declaring class has `@Stateless` or `@Singleton`, would you please review? Thanks :)

But as you said, it needs update in `org.jboss.resteasy.resteasy-cdi`'s `module.xml` to depend on `javax.ejb.api` to work, so CI failed, do you have any idea how to pass the CI for Resteasy?

**Comment by bmaxwell** [comment]
retest this please!

**Comment by ronsigal** [comment]
Hi @bmaxwell,

re: "retest this please"

Actually, I'll be submitting an alternative pull request soon.

-Ron

**Comment by gaol** [comment]
close the PR as Ron will come up with alternative one

**Pull request closed without merging**
