### PR TITLE
Fix issue with Spring Web parameters encoding

### PR DESCRIPTION
**Pull request by geoand**
Fixes: https://github.com/quarkusio/quarkus/issues/10133

### CODE REVIEW

**Comment by geoand** [comment]
Ideally we would have this backported to 4.5.x :)

**Comment by geoand** [comment]
cc @asoldano

**Comment by asoldano** [comment]
@geoand how difficult would it be to provide a testcase for this?

**Comment by geoand** [comment]
Should be easy, I'll try and add oen

**Comment by geoand** [comment]
Test added

**Comment by geoand** [comment]
Thanks @asoldano

**Pull request merged**
