### PR TITLE
[RESTEASY-1927] ClientResponseContextImpl: getEntityStream returns possibly exhausted inputStream

### PR DESCRIPTION
**Pull request by stevenschlansker**
Currently, a response filter that chooses to read the response context's `getEntityStream` is returning the `inputStream`.
This is fine if the stream has not been read already.  But if it ends up being buffered, either internally or via `bufferEntity()`, the input stream is exhausted.

Returning the entity stream from the response fixes this issue.

### CODE REVIEW

**Comment by stevenschlansker** [comment]
cc @mikebell90 @pennello @strykerd @rushalias

**Comment by stevenschlansker** [comment]
Thanks for sharing your hunch, I think you might be right.  I've attempted to fix this by resetting the buffered entity, e.g.

```diff
     @Override
     protected void setInputStream(InputStream is) {
         stream = is;
+        streamFullyRead = false;
+        entity = null;
     }
```

but this additional change appears to break some tests which check buffered exception responses.  I'll continue digging in.

**Comment by stevenschlansker** [comment]
Hm, I cannot reproduce the test failures I saw yesterday.  @asoldano do you think the fix of resetting the entity, so it re-processes the stream, is correct for the issues you highlighted above?  It seems reasonable to me but I understand this is probably a touchy area of the code.

**Comment by stevenschlansker** [comment]
Ok, I understand the test failure now.  `AbortedResponse` should not reset the entity, since it might be provided directly rather than being set by stream.

**Comment by asoldano** [comment]
Thanks!

**Pull request merged**
