### PR TITLE
[RESTEASY-2974] ClientConfiguration.toString(null, type, annotations) causes NPE

### PR DESCRIPTION
**Pull request by petrberan**
https://issues.redhat.com/browse/RESTEASY-2974

### CODE REVIEW

**Comment by jamezp** [comment]
Thank you for the contribution. We are cleaning up older PR's that seem to be stale. If you feel this is still an issue please feel free to re-open.

**Review by jamezp — COMMENTED** [review]
Overall I'm not too sure about this. The `ParamConverter` is pretty explicit that an `IllegalArgumentException` should be thrown if a parameter is null, https://jakarta.ee/specifications/restful-ws/3.1/apidocs/jakarta.ws.rs/jakarta/ws/rs/ext/paramconverter. I'm tempted to reject the JIRA in general based on that. Unfortunately, the reporter is not active on JIRA any longer.

**Comment by petrberan** [comment]
@jamezp  I tried to reproduce the issue today and I cannot get the same error as described in the issue, since parent methods for toString() are checking for null. I have no idea how I managed to reproduce it last time, but since the behavior is more or less according to specs, I'd vote for resolving this one as Won't do. Or have you by any chance managed to get a reproducer?

That being said, the ParamConverter specs do not restrict IAE for PathParam only, but also to MatrixParam, QueryParam etc, yet I was able to run some tests passing null arg to other params without any error. Is that alright?

**Comment by jamezp** [comment]
I was able to reproduce it, but really I think we shouldn't be bypassing what the JavaDoc indicates should be done here. For that reason I'll close this and reject the JIRA based on that. Thank you @petrberan for all the work on this.

**Pull request closed without merging**
