### PR TITLE
Cache result of computation of ResteasyUriInfo

### PR DESCRIPTION
**Pull request by geoand**
Relates to: https://github.com/quarkusio/quarkus/issues/4345

This PR is meant to eliminate with such async-profiles results:

```
--- 2755952637848 bytes (0.82%), 88 samples
  [ 0] int[]
  [ 1] java.util.regex.Matcher.<init>
  [ 2] java.util.regex.Pattern.matcher
  [ 3] org.jboss.resteasy.util.Encode.decodePath
  [ 4] org.jboss.resteasy.specimpl.ResteasyUriInfo.initialize
  [ 5] org.jboss.resteasy.specimpl.ResteasyUriInfo.<init>
  [ 6] io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo
  [ 7] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch
  [ 8] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext
  [ 9] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0
  [10] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$$Lambda$211.2038650648.handle
  [11] io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2
  [12] io.vertx.core.impl.ContextImpl$$Lambda$216.1802137975.run
  [13] java.util.concurrent.ThreadPoolExecutor.runWorker
  [14] java.util.concurrent.ThreadPoolExecutor$Worker.run
  [15] io.netty.util.concurrent.FastThreadLocalRunnable.run
  [16] java.lang.Thread.run
```
,

```
--- 1386496101488 bytes (0.41%), 44 samples
  [ 0] char[]
  [ 1] java.lang.AbstractStringBuilder.<init>
  [ 2] java.lang.StringBuilder.<init>
  [ 3] org.jboss.resteasy.util.Encode.decodePath
  [ 4] org.jboss.resteasy.specimpl.ResteasyUriInfo.initialize
  [ 5] org.jboss.resteasy.specimpl.ResteasyUriInfo.<init>
  [ 6] io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo
  [ 7] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch
  [ 8] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext
  [ 9] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0
  [10] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$$Lambda$211.2038650648.handle
  [11] io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2
  [12] io.vertx.core.impl.ContextImpl$$Lambda$216.1802137975.run
  [13] java.util.concurrent.ThreadPoolExecutor.runWorker
  [14] java.util.concurrent.ThreadPoolExecutor$Worker.run
  [15] io.netty.util.concurrent.FastThreadLocalRunnable.run
  [16] java.lang.Thread.run
```

and 

```
--- 1221202338200 bytes (0.36%), 39 samples
  [ 0] java.lang.Object[]
  [ 1] java.util.Arrays.copyOf
  [ 2] java.util.ArrayList.grow
  [ 3] java.util.ArrayList.ensureExplicitCapacity
  [ 4] java.util.ArrayList.ensureCapacityInternal
  [ 5] java.util.ArrayList.add
  [ 6] org.jboss.resteasy.specimpl.PathSegmentImpl.parseSegmentsOptimization
  [ 7] org.jboss.resteasy.specimpl.ResteasyUriInfo.processPath
  [ 8] org.jboss.resteasy.specimpl.ResteasyUriInfo.initialize
  [ 9] org.jboss.resteasy.specimpl.ResteasyUriInfo.<init>
  [10] io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo
  [11] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch
  [12] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext
  [13] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0
  [14] io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$$Lambda$211.2038650648.handle
  [15] io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2
  [16] io.vertx.core.impl.ContextImpl$$Lambda$216.1802137975.run
  [17] java.util.concurrent.ThreadPoolExecutor.runWorker
  [18] java.util.concurrent.ThreadPoolExecutor$Worker.run
  [19] io.netty.util.concurrent.FastThreadLocalRunnable.run
  [20] java.lang.Thread.run
```

Quarkus builds `ResteasyUriInfo` at: https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/VertxUtil.java#L47

During my performance testing I found that the patch consistently improved the average and max latency by a little.

@Sanne would you like to give it a shot and see how it goes?

### CODE REVIEW

**Comment by geoand** [comment]
@asoldano excellent point!

Let me check and see if we can do anything about that.

**Comment by geoand** [comment]
I was able to get around the problem of erroneous URLs with a small refactoring of this and a change in Quarkus. 
However there is still a problem with `@PathParam`. This could be mitigated with the use of an expiring map but we don't have any of those so I'll close this for now and we can perhaps revisit in the future if it's really needed.

**Comment by Sanne** [comment]
Couldn't you use a bounded concurrent map? It's a cache after all.

**Comment by asoldano** [comment]
eh, I just commented the same in the other thread ;)

**Comment by geoand** [comment]
I wasn't aware of that class. Let me check and revert

**Comment by geoand** [comment]
BoundedConcurrentMap is in Hibernate, is it not?

**Pull request closed without merging**
