### PR TITLE
RESTEASY-1151 Upgraded Jackson to version 2.5.3 (from 2.4.1).

### PR DESCRIPTION
**Pull request by awhitford**

### CODE REVIEW

**Comment by ronsigal** [comment]
The Resteasy testsuite passes with this upgrade.

**Comment by ronsigal** [comment]
Wildfly 9.0.0.CR3-SNAPSHOT uses Jackson 2.5.1, so we'll probably use that.

**Comment by liweinan** [comment]
Thanks Ron :-) Please let me know if you want to merge it.

**Comment by ronsigal** [comment]
I was probably unclear. Shouldn't the dependency be on 2.5.1?

**Comment by liweinan** [comment]
It has been upgraded to 2.6.3

**Pull request closed without merging**
