### PR TITLE
Vertx server adapter

### PR DESCRIPTION
**Pull request by vietj**
Integration with Vert.x 3.3

### CODE REVIEW

**Comment by jimma** [comment]
Hi Julien, 
Is callEmpty(client) in JaxrsAsyncTest for 3 times intended ?  
For the new added RESTEASY1323Test , RESTEASY1325Test, if these issues are already verified by tests in resteasy-netty4 module, do we need to check in vertx module again ? 
Thanks

**Comment by vietj** [comment]
@jimma to be honest I just copied the Netty tests as Vert.x and Netty are very similar, we can remove these tests if you think it's better - I have no strong opinion on this.

**Comment by vietj** [comment]
@jimma call callEmpty, again I copied the Netty 4 tests, that do the same

**Comment by jimma** [comment]
I'll merge and fix these tests later.

**Comment by vietj** [comment]
@jimma thanks!

**Comment by vietj** [comment]
@jimma any idea when this will be in a Resteasy release ?

**Comment by asoldano** [comment]
Likely in a beta release by the end of this week

**Comment by vietj** [comment]
great, don't hesitate to ping us when it's done and perhaps you can announce it to the Vert.x google group as well ?

**Comment by asoldano** [comment]
I've committed a small fix to change the scope of a maven dependency, as the merged commits were breaking the build.
Besides that, I've created https://issues.jboss.org/browse/RESTEASY-1453 , can you please fill in the description / provide some details so that the addition is tracked in the release notes?
It would also be cool if you could provide a bit of documentation, otherwise we'll manage to write something ;-)

**Comment by vietj** [comment]
Hi,

I added a section in the Resteasy docbook, what else do you expect ?

**Comment by vietj** [comment]
I have added a comment as I could not find a way to edit a description in the JIRA task.

**Comment by asoldano** [comment]
@vietj thanks; actually I missed the changed to the docbook, so we're fine :-)
Last thing, the VertxContainer is in package org.jboss.resteasy.test... I assume that's a mistake and I'd move that to package org.jboss.resteasy.plugins.server.vertx, ok?

**Comment by jimma** [comment]
@vietj , I removed some tests from your change and clean up some imports. Can you please have a look at this PR https://github.com/resteasy/Resteasy/pull/880 ? If it's OK, I am going to merge it. Thanks.

**Comment by vietj** [comment]
@jimma n/p with me,  how does 880 relates to vertx ?

**Comment by vietj** [comment]
@asoldano ok for moving this to a more appropriate place (I copied what netty did)

**Comment by jimma** [comment]
Should be PR https://github.com/resteasy/Resteasy/pull/883. Sorry.
> @jimma n/p with me, how does 880 relates to vertx ?

**Pull request merged**
