### PR TITLE
Cleanup httpclient dependencies for resteasy-core

### PR DESCRIPTION
**Pull request by electrum**
Remove unused dependencies from `resteasy-core` and `resteasy-core-spi`,
and add dependencies that were being depended on transitively.

### CODE REVIEW

**Comment by asoldano** [comment]
Thanks @electrum for the contribution. Before I merge your PR, please note that we require all contributions to be made under the terms of the ASL2.0 License: http://www.apache.org/licenses/LICENSE-2.0 Do you agree to these terms?

**Comment by asoldano** [comment]
As the changes are really just a re-org of the maven dependency tree, I believe I can move forward with the merge. @electrum still please formally approve your agreement with the ASL2.0 License (mainly for future contributions :-))

**Comment by electrum** [comment]
I agree to these terms. Do I need to also sign a CLA?

**Comment by asoldano** [comment]
No, it's fine like this, thanks.

**Pull request merged**
