### PR TITLE
CDI BeanManager fix for Quarkus 

### PR DESCRIPTION
**Pull request by phillip-kruger**
This is a fix for an issue in Quarkus (https://github.com/quarkusio/quarkus/pull/7639) that is currently  
temporarily fixed inside the Quarkus Extension (https://github.com/quarkusio/quarkus/pull/7639)
 
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by phillip-kruger** [comment]
@asoldano @stuartwdouglas please have a look (I can not assign reviewers :) )

**Comment by asoldano** [comment]
thanks @phillip-kruger ; I believe @ronsigal is the one who should really review this, as he provided the original implementation. Thanks!

**Comment by ronsigal** [comment]
Hi @phillip-kruger,

I'm re-running the failed tests and also running the testsuite on my laptop.

I have a question and a comment:

1. What are you seeing that suggests moving the acquisition of the BeanManager out of observeBeforeBeanDiscovery()? Was it getting a null BeanManager?

2. There are a few places in RestClientExtension.construct() where the manager variable is assumed to have a non-null value. With your changes, manager will get assigned in isCDIActive(). Now the only place where construct() is called is in ClientHeaderProviders.getCustomHeadersFactory():

```
if (RestClientExtension.isCDIActive()) {
    Object factory = RestClientExtension.construct(factoryClass);
```
so it's safe, at least for now. But what if the code changes in the future? Maybe there should be a test at the beginning of construct() that verifies that manager != null or acquires a value.

-Ron

**Comment by phillip-kruger** [comment]
Hi @ronsigal - thanks for getting back to me. 

1) Yes, 
`public void observeBeforeBeanDiscovery(@Observes BeforeBeanDiscovery event, BeanManager beanManager)` does not work in Quarkus. So even if CDI is active, the manager is never set.

2) Agree. This was an issue even before my change. I did not want to do a null check, as some other code might rely on a NullPointerException, but if you agree that we should then I am happy to add that. Let me know.

**Comment by ronsigal** [comment]
Hey @phillip-kruger,

Yeah, I think it's reasonable to do the null check.

The same test (SSETest in resteasy-vertx) is still failing in the jdk 11 runs. I'm running the testsuite with jdk 11 on my laptop to see what happens. It doesn't seem like your change should affect an SSE test, but I'll have to look into it. If you have any insights, they would be welcome. ;-)

**Comment by phillip-kruger** [comment]
Hi @ronsigal . Ok I am adding a null check to this PR. Thanks

**Comment by phillip-kruger** [comment]
@ronsigal - please check again. Now with CDI checking in the `RestClientExtension.construct()` method

**Comment by ronsigal** [comment]
re: "I am adding a null check to this PR."

Thanks, @phillip-kruger.

It looks like the intermittent test failures come from a recent unrelated change. Still looking.

**Comment by phillip-kruger** [comment]
Thanks @ronsigal - Please let me know if there is anything I can help with.

**Comment by asoldano** [comment]
Thanks @ronsigal for the checks and @phillip-kruger for the discussion. The intermittent failure is unrelated, so I'm merging this.

**Pull request merged**
