### PR TITLE
[JBEAP-17580] Fixing private PostConstruct method detection

### PR DESCRIPTION
**Pull request by spyrkob**
port of #2036 for 3.6.1.SPx branch

JIRA: https://issues.jboss.org/browse/JBEAP-17580
Upstream: https://issues.jboss.org/browse/RESTEASY-2249
Upstream PR: #2036

### CODE REVIEW

**Comment by spyrkob** [comment]
@ronsigal looking at travis logs it seems it failed trying to install java 8 - is there some env issue with CI?

**Comment by ronsigal** [comment]
Hi @spyrkob,

Yes, it's a travis thing. I tried fixing it last night, not entirely successfully, and then Jim Ma fixed my fixes. I'm testing it now. 

-Ron

**Comment by ronsigal** [comment]
@spyrkob, the tests should pass now, but I think you have to rebase in order to pick up the latest travis configuration.

**Comment by spyrkob** [comment]
Looks better now, thanks @ronsigal :)

**Pull request merged**
