### PR TITLE
update InjectorFactory in ResourceMethodInvoker 

### PR DESCRIPTION
**Pull request by zhuyou1234**
let  InjectorFactory in ResourceMethodInvoker can be definition by every method, such as define a custom DynamicFeature for special method, and add a special method InjectorFactory for some special args validation.

### CODE REVIEW

**Comment by jamezp** [comment]
@zhuyou1234 Are you seeing an issue with this? I don't really follow the requirement for the change.

**Comment by zhuyou1234** [comment]
> @zhuyou1234 Are you seeing an issue with this? I don't really follow the requirement for the change.

In one scenario, for REST resources, for some interfaces, we need to verify whether the accepted jsonObject Payload is a JSONSchema that meets certain criteria. If we can extend this, InjectFactory can also be customized by dynamicFeature, isn't it much easier to implement?

**Comment by zhuyou1234** [comment]
> @zhuyou1234 Are you seeing an issue with this? I don't really follow the requirement for the change.

**Comment by zhuyou1234** [comment]
> @zhuyou1234 Are you seeing an issue with this? I don't really follow the requirement for the change.



> @zhuyou1234 Are you seeing an issue with this? I don't really follow the requirement for the change.

this is a enhance function

**Comment by zhuyou1234** [comment]
> @zhuyou1234 Are you seeing an issue with this? I don't really follow the requirement for the change.

this is a enhance function

**Comment by zhuyou1234** [comment]
> @zhuyou1234 Are you seeing an issue with this? I don't really follow the requirement for the change.

**Comment by jamezp** [comment]
Thank you for the contribution. We are cleaning up older PR's that seem to be stale. If you feel this is still an issue please feel free to re-open.

**Pull request closed without merging**
